### ISSUE TITLE
Addon car names[Could u help me] 

### ISSUE THREAD

**Issue by ProtecalExdee** [HumanTree92/esx_advancedgarage#103]
Hey i was wonderling how to add the lua with the custome car names

[Must setup a vehicle_names.lua for Custom Addon Vehicles.]

iam new to scripting and alll this so could u help me with this

wfr
Larry

**Comment by HumanTree92** [comment]
https://github.com/HumanTree92/esx_advancedgarage/wiki/Common-Fixes

**Comment by ProtecalExdee** [comment]
thx dude btw merry christmas
