### ISSUE TITLE
No vehicles in Garage

### ISSUE THREAD

**Issue by Phantom213** [HumanTree92/esx_advancedgarage#105]
When i buy a car, and i park it, the Garge say i have no car, and i becomme this error. 

SCRIPT ERROR: @esx_advancedgarage/client/main.lua:536: attempt to index a nil value (field 'value')
> ref (@esx_advancedgarage/client/main.lua:536)
> handler (@es_extended/client/functions.lua:1316)

**Comment by ChaosPower** [comment]
@Phantom213 ,

Please check `AND job = @Job` this will produce in query as `AND job = ''`. The default value in mysql is at fault here. Instead of putting in data type string `''` it is at default `NULL`

**Comment by HumanTree92** [comment]
Fixed in 535cb2b40bbce6e6ad94ad651f32a3e12f9e2aa3

The problem was the job = '',

To simply fix the issue just edit your owned_vehicles & change the job to NOT NULL & DEFAULT to civ
