### ISSUE TITLE
Cars don't save in garage

### ISSUE THREAD

**Issue by FivePageGames** [HumanTree92/esx_advancedgarage#106]
Hey, when I buy a new car from the shop it says that I purchased it and all and it adds it to the database but when I try to get the car from the garage it's not in there.

https://gyazo.com/feb0daf62bc74848ee14012a03e8c648

**Comment by ChaosPower** [comment]
@FivePageGames ,

Your screenshot is wrong, please provide query output.

Ty.

**Comment by HumanTree92** [comment]
Implementing my vehicleshopfix.sql would fix this. Sadly i don't have much time on my hands to work on fixing it for good. I will try to get it done ASAP.

**Comment by HumanTree92** [comment]
Fixed in 535cb2b40bbce6e6ad94ad651f32a3e12f9e2aa3

The problem was the job = '',

To simply fix the issue just edit your owned_vehicles & change the job to NOT NULL & DEFAULT to civ
