### ISSUE TITLE
Vehicle modifications not saving

### ISSUE THREAD

**Issue by FlawwsX** [HumanTree92/esx_advancedgarage#107]
Hi,

I have a problem with vehicle mods not saving. I looked through everything and the issues but no resolution was found. This is for all cars, including default GTA.

Thanks.

**Comment by tonibanks** [comment]
Same this happen after update of extended

**Comment by HumanTree92** [comment]
Similar to https://github.com/HumanTree92/esx_advancedgarage/issues/75 comment there if still having issues
