### ISSUE TITLE
client main.lua 220

### ISSUE THREAD

**Issue by danbaker1986** [HumanTree92/esx_advancedgarage#108]
![car error](https://user-images.githubusercontent.com/59373505/72638406-46272880-395b-11ea-89c6-78305fa2adbb.PNG)
![car error1](https://user-images.githubusercontent.com/59373505/72638425-4f17fa00-395b-11ea-845e-0be75e4a5d05.PNG)

**Comment by HumanTree92** [comment]
For starters i would make sure your using the latest update.

**Comment by danbaker1986** [comment]
I thought that was the updated version
ive looked alround for solution before asking

**Comment by HumanTree92** [comment]
Not sure where you got this from. No where in my client/main.lua do i have a TriggerServerEvent for setVehicleFuel

**Comment by HumanTree92** [comment]
I would also make sure that you are using my vehicleshop_fix.sql

**Comment by danbaker1986** [comment]
okay so where do I get the up to date files if the one I have isn't
the one I have has the fix sql, and I added it

**Comment by danbaker1986** [comment]
its from you the one I have as its in the read me

**Comment by HumanTree92** [comment]
Like every script that i do i don't rely i Releases. Just go to [here](https://github.com/HumanTree92/esx_advancedgarage) and click on clone or download then click on download zip

**Comment by danbaker1986** [comment]
ok thanks, same one i have

**Comment by HumanTree92** [comment]
No its not the same unless u have edited the code. B/c for your lines 215-231 are way different then the files current lines 215-231

**Comment by HumanTree92** [comment]
Your issue states there is a problem on line 220. But in my files line 220 is -- List Owned Boats Menu

**Comment by HumanTree92** [comment]
If u can send me all the files for the esx_advancedgarage script that you have.

**Comment by danbaker1986** [comment]
[esx_advancedgarage-master.zip](https://github.com/HumanTree92/esx_advancedgarage/files/4079121/esx_advancedgarage-master.zip)

here the file I got

**Comment by danbaker1986** [comment]
and it has what I have

**Comment by HumanTree92** [comment]
Did u edit the files or was it downloaded from somewhere else. Also send me a picture of your owned_vehicles structure

**Comment by danbaker1986** [comment]
no that's the file I got off github

**Comment by danbaker1986** [comment]
![owner](https://user-images.githubusercontent.com/59373505/72647416-7200d900-3970-11ea-8cfa-acb91577fc7c.PNG)

**Comment by HumanTree92** [comment]
The owned_vehicle table looks fine. But i can say that the files you have are not all mine. It is an edited version of mine. However i do not support edits and i would talk to the person who made the edits or try using my version without all those edits.

**Comment by HumanTree92** [comment]
You can clearly see the difference for the server files [here](https://www.diffchecker.com/HvYunBYn) and the client files [here](https://www.diffchecker.com/WAFh15XW)

**Comment by danbaker1986** [comment]
yeah I can see

**Comment by danbaker1986** [comment]
so just swap files over?

**Comment by danbaker1986** [comment]
ill use yours, as that is what I thought I had
