### ISSUE TITLE
Cannot store car in garage

### ISSUE THREAD

**Issue by Patrickstek121** [HumanTree92/esx_advancedgarage#11]
Hello,

I download your awesome code first of all thankyou for this! but i have a problem.

I get this errror.

![image](https://user-images.githubusercontent.com/16652731/54836969-9b57c680-4cc5-11e9-8087-2ebcf21a0ae9.png)

do you know how to fix this?

**Comment by HumanTree92** [comment]
Please checkout this https://github.com/HumanTree92/esx_advancedgarage/issues/7 as this is the same issue that i haven't gotten to yet. Been busy with RL stuff.
