### ISSUE TITLE
No Vehicles in Garage

### ISSUE THREAD

**Issue by realCrytex** [HumanTree92/esx_advancedgarage#111]
If i buy a car, it gets an entry in the database, however it does not show up in the Garage or Impound. I even tried installing an older Version of the Script which seemed to change nothing.

**Comment by HumanTree92** [comment]
Please post image of your owned_vehicles structure.

**Comment by realCrytex** [comment]
Yeah no nvm found the mistake maybe fix your vehicleshopfix sql its altering the table wrong
