### ISSUE TITLE
Script Error when trying to inbound/store vehicles

### ISSUE THREAD

**Issue by Yedoo** [HumanTree92/esx_advancedgarage#112]
Hey! I'm getting this script erro:

SCRIPT ERROR: @esx_advancedgarage/server/main.lua:337: attempt to index a nil value (local 'account')
> ref (@esx_advancedgarage/server/main.lua:337)
> handler (@esx_addonaccount/server/main.lua:63)
> handler (@esx_advancedgarage/server/main.lua:336)

**Comment by HumanTree92** [comment]
What's the society name for ur mechanic job. It should look like society_mechanic and not society_mecano
