### ISSUE TITLE
Parking brake/Disabled Vehicle?

### ISSUE THREAD

**Issue by ResqDiver1317** [HumanTree92/esx_advancedgarage#114]
I was wondering if there was anything in AdvancedGarage that would cause a vehicle to behave like it had a parking brake set/disabled from moving under certain conditions? We have had several times now where we will have our owned vehicle out and for various reasons, will hop in and drive another one for a few minutes and when we come back to ours and get it, it won't move. It acts like it's trying to move against a really good parking brake (I mean REALLY good, as in slam it with a semi and it doesn't budge good). I was wondering if this was possibly something with AdvancedGarage trying to treat it as a "lost" vehicle and freezing it, but wasn't sure so I figured I'd ask and see if that may be the case or if not, maybe someone has an idea what might be causing this and how to fix it. 

(for anyone wondering why we would drive a diff vehicle here is the example that happened today. I'm the Fire Chief on our server and was "off duty" in my personal vehicle and came up on a MVA with several vehicles while on my way to get fuel. I stopped and started working the scene until more of my personnel could arrive. Once my personnel took over, I went to move my truck and noticed the fuel level was low enough I didn't think it would make it to the station so I took one of the extra FD vehicles from the scene and ran to the gas station to fill a Jerry Can, came back, fueled my personal vehicle but when I went to drive away, it was stuck in middle of the street and could not be moved. We tried to shove it off the road with one of the Fire Engines but it would not budge at all. Even tried having a tow truck load it but still nothing. I ended up having to use /dv to get rid of it then go recover it from impound).

**Comment by HumanTree92** [comment]
This script doesn't have any effect of vehicles at all. I would check some of your other scripts to see if they make changes to vehicles.
