### ISSUE TITLE
You can not store this vehicle 

### ISSUE THREAD

**Issue by rezak164** [HumanTree92/esx_advancedgarage#115]
esx_advancedgarage: steam:110000118954b7c attempted to store an vehicle they don
't own!

You Can Not Store this vehicle

Please Help Me :(

**Comment by HumanTree92** [comment]
This is going to be fixed in the next big update. Currently ATM i don't have the time to fix this issue. ESX has decided to ditch steam & use rockstar

**Comment by rezak164** [comment]
oh nice now im use previous update  es_extended and work?

**Comment by rezak164** [comment]
You can give me time fixed?
@HumanTree92

**Comment by rezak164** [comment]
fixeD?

**Comment by HumanTree92** [comment]
Should be fixed in 1ebad6d80c2183a462d3dc64d975d426af63af55
