### ISSUE TITLE
Markers

### ISSUE THREAD

**Issue by wallierocks2001** [HumanTree92/esx_advancedgarage#116]
How would i make the markers different types for each 

eg. a car for where you get it out 
      a dollar-sign for impound

I know the marker numbers

**Comment by HumanTree92** [comment]
You will have to edit the DrawMarker for each place. I currently have it set to use Config.MarkerType i will add it in a future update that players can edit the marker types in the config.lua but for now you will have to change it in the client/main.lua

**Comment by wallierocks2001** [comment]
Thanks will give that a go

**Comment by wallierocks2001** [comment]
I did that however it's still not working
