### ISSUE TITLE
Cant take any car from garage

### ISSUE THREAD

**Issue by rex2630** [HumanTree92/esx_advancedgarage#119]
It says i dont own any...

**Comment by HumanTree92** [comment]
Image of your owned_vehicles structure?

**Comment by rex2630** [comment]
![image](https://user-images.githubusercontent.com/30006554/75629348-8aa41600-5be1-11ea-9477-55a64e66c391.png)

**Comment by rex2630** [comment]
![image](https://user-images.githubusercontent.com/30006554/75629355-adcec580-5be1-11ea-8189-df688ee97db7.png)

**Comment by HumanTree92** [comment]
In the newest version you must have job default set as civ or you can change the code to how you want it.

**Comment by rex2630** [comment]
What? Job? U need to have job for parking vehicles?

**Comment by rex2630** [comment]
I think that i know what u mean

**Comment by HumanTree92** [comment]
No. I take it the 2nd image is your owned_vehicles. You currently have the default value for job set at '' when it needs to be civ i have done it this way b/c leaving it blank is dumb.

**Comment by HumanTree92** [comment]
I mainly did it this way b/c when police buy vehicles the job is set to police & for ambulance is set to ambulance. So in my case i have it set to civ for unemployed

**Comment by rex2630** [comment]
thanks for help
