### ISSUE TITLE
errors in console.

### ISSUE THREAD

**Issue by Ultrunz** [HumanTree92/esx_advancedgarage#12]
```
es_extended: TriggerServerCallback => [esx_advancedgarage:getOwnedProperties] does not exist
```
I have tried a few times to fix it but cant get it to work. 

I originally had the Database error that was fixed by changing stored to 'stored' on line 11.

![image](https://user-images.githubusercontent.com/13288425/54868671-911af280-4dc1-11e9-8dd9-970283b31e64.png)

I have also tried a few fixes from here.
https://github.com/HumanTree92/esx_advancedgarage/issues/8
but to no avail. Everything is 100% stock on the script. A fresh download apart from that first fix for 'stored' which fixed the database error I had

**Comment by HumanTree92** [comment]
What are you trying to do. As both of those callbacks are clearly there.

**Comment by Ultrunz** [comment]
I know. I havent changed anything. These pop up when I go to the marker to take out the car.

the property one came when i tried to store a car

I checked the code too and i saw all the callbacks so it confused me. 

just wondered what was going on

**Comment by HumanTree92** [comment]
Could u send me ur Mod Load order. As that could be the problem.

**Comment by Ultrunz** [comment]
Well its not on at the moment because of the errors. where should it start?

its normally just among the esx section i have. probably more towards the bottom.

**Comment by Ultrunz** [comment]
Im going to put it back on, its started just after vehicleshop now. I will let you know if the errors come up

**Comment by HumanTree92** [comment]
Yeah this mod should be loaded after is required scripts. If not it will always throw errors.
