### ISSUE TITLE
Je ne peut pas ranger mon vehicule 

### ISSUE THREAD

**Issue by hmzoud** [HumanTree92/esx_advancedgarage#120]
Bonjour j'y arrive pas a ranger mon vehicule dans le garage j'ai ça comme erreur si vous pouvez m aidé svp j ai bien rajouter le sql manquant mais rien a faire ?

![](https://cdn.discordapp.com/attachments/666004274630885396/684134546723438665/unknown.png)

**Comment by HumanTree92** [comment]
I have no clue what you are saying. ENGLISH ONLY
