### ISSUE TITLE
Car not spawning

### ISSUE THREAD

**Issue by Rado236** [HumanTree92/esx_advancedgarage#123]
I added my car to vehicle_names.lua also added the file to fxmanifest and I still cannot get my car?? It says that I have no cars.

**Comment by HumanTree92** [comment]
Did you follow the [Wiki](https://github.com/HumanTree92/esx_advancedgarage/wiki/Common-Fixes)

If you did please post an image of your owned_vehicles structure.

**Comment by Rado236** [comment]
I created owned_vehicles_old and it somehow fixed
