### ISSUE TITLE
When Buying from esx_vehicleshop issue

### ISSUE THREAD

**Issue by HurtHurt** [HumanTree92/esx_advancedgarage#124]
When i Purchase a car from esx_vehicleshop it says i have purchased the car but wont set the plate on it? i have upgraded and downgraded my esx_vehicleshop several times and still nothing will work any help? thanks for your time

**Comment by HurtHurt** [comment]
I am using the newest version of both ATM

**Comment by HumanTree92** [comment]
If esx_vehicleshop is the problem go there for help.
