### ISSUE TITLE
The cars i buy and put in the garage also disappear, but it says a different error code

### ISSUE THREAD

**Issue by Asset2K** [HumanTree92/esx_advancedgarage#125]
![error](https://user-images.githubusercontent.com/62441410/77190645-4e7a1c00-6ae2-11ea-9fb1-2126b6bef3c0.png)
There is the error code it is giving me. or here it is

script error: @esx_advancedgarage/client/main.lua:209: attempt to index a nil value (field 'value')

Please help

**Comment by rolocyenom** [comment]
I am encountering some issues as well. I've uploaded the sql fix and that hasn't fixed anything.

**Comment by Davidas59** [comment]
and my bad

**Comment by HumanTree92** [comment]
If using zap hosting don't use them. Their trash. Make sure you are using the latest updates of es_extended.

**Comment by HumanTree92** [comment]
That error was due to clicking on a spacer. This is now fixed in d5b104d02ebe2b38293571ec8d21c6addf8f9b4a
