### ISSUE TITLE
Cannot take vehicle out of impound or personal garage

### ISSUE THREAD

**Issue by dutchplayers** [HumanTree92/esx_advancedgarage#129]
Hi,

Thanks for the resource.

If we buy a property we can store a car, but i can't take it out. Just no vehicle is in there.

But also, i found no car in my impound... If opening the impound i got this error:

client/main.lua:516: attempt to index a nil value (field value)

**Comment by HumanTree92** [comment]
Do u use zap hosting?

**Comment by clink182** [comment]
https://github.com/HumanTree92/esx_advancedgarage/wiki/Common-Fixes

Take a look at this, match your database to the example, and you'll be golden, pony boy.
Worked perfect for me.
