### ISSUE TITLE
Can you send me what u used for the config lines 14-38

### ISSUE THREAD

**Issue by TedakCZE** [HumanTree92/esx_advancedgarage#130]
Can you send me what u used for the config lines 14-38

_Originally posted by @HumanTree92 in https://github.com/HumanTree92/esx_advancedgarage/issues/8#issuecomment-465745373_

Problem fix is change to steamid

IM not good fix and work change 

Please how to make oné account from users 

esplugin_mysql
es_extended 
esx_identity
esx_advancedgarage

How to make one load accound?

My server join make two accound 

One steam
Two normál 
Identifikation(owner)

**Comment by HumanTree92** [comment]
Maybe you should update to the latest of everything. If you are using Zap hosting don't use their update script. This script supports the latest es_extended. On the config lines i am using the default from the download except i also have Config.GiveSocietyMoney = true

**Comment by TedakCZE** [comment]
Make two account how to fix please
IM search how to fix duplications users

**Comment by TedakCZE** [comment]
![1585918061125280820463753972849](https://user-images.githubusercontent.com/63079673/78362262-1979c900-75ba-11ea-96ad-6868c2ef3b51.jpg)

**Comment by HumanTree92** [comment]
The problem you are having is nothing related to my script. I can tell you that the column `license` is not used by any ESX Script. It is used by `esplugin_mysql` but in the new updates of ESX they have ditched ES completely as noted [here](35a726685e81c7e74d13e05d6f9b8e4d5f9bea23).
