### ISSUE TITLE
Fixxed vehicleshop for vehicle withdraw but in

### ISSUE THREAD

**Issue by zBombard** [HumanTree92/esx_advancedgarage#131]
![image](https://user-images.githubusercontent.com/17300088/78338226-a9a41800-7592-11ea-81bf-cada2ba1d644.png)

I dont understand why i've got this problem (even reinstalled database)

This is my server.cfg

![image](https://user-images.githubusercontent.com/17300088/78338293-cf312180-7592-11ea-9535-e6e17a9da74b.png)

PS: "It is Possible to Duplicate Vehicles but do note that if said Person Duplicates a Vehicle & takes 1 of them & sell thems the other one is useless & can NOT be stored or sold."
Can't you add a code if vehicle plate is already spawned u cant take it from impound? 

Sorry for my bad english anyway and thx for ur supp

**Comment by HumanTree92** [comment]
No that isn't possible.

**Comment by zBombard** [comment]
However i've understand the problem
If u press this error occurs
![image](https://user-images.githubusercontent.com/17300088/78349085-55edfa80-75a3-11ea-8721-cfd288075d0a.png)

**Comment by HumanTree92** [comment]
Yeah so i've got an update to fix some issues. Also just as an update i see that you are using essentialmode. You will run into problems with the updates as ESX has completely ditched ES as noted [here](35a726685e81c7e74d13e05d6f9b8e4d5f9bea23)
