### ISSUE TITLE
attempt to call a nil value (field 'RegisterCommand')

### ISSUE THREAD

**Issue by nhytros** [HumanTree92/esx_advancedgarage#133]
Don't run for me. When started the followin error is displayed:
Creating script environments for esx_advancedgarage
Error loading script server/main.lua in resource esx_advancedgarage: @esx_advancedgarage/server/main.lua:26: attempt to call a nil value (field 'RegisterCommand')
stack traceback:
        @esx_advancedgarage/server/main.lua:26: in main chunk
Failed to load script server/main.lua.

**Comment by HumanTree92** [comment]
you must not have everything updated. Go into the config.lua and set Config.UseCommand to false

**Comment by HumanTree92** [comment]
Quick update the reason this doesn't work is b/c you are not using the latest comments to es_extended.
