### ISSUE TITLE
no blip for the private garages

### ISSUE THREAD

**Issue by Rado236** [HumanTree92/esx_advancedgarage#134]
Hi! The script is great! But I dont get the blips of the private garages.I set the option in the config.lua file to true but they still dont show up.
![20200413130703_1](https://user-images.githubusercontent.com/55925335/79167176-875e9580-7def-11ea-8cef-3ee3ccaaad65.jpg)

**Comment by HumanTree92** [comment]
Private garages only show when you own that property. You must also follow the [Wiki Guide #7](https://github.com/HumanTree92/esx_advancedgarage/wiki/Common-Fixes) to have it work with esx_property to load the garages when you buy it.
