### ISSUE TITLE
Not seeing blips

### ISSUE THREAD

**Issue by overdam** [HumanTree92/esx_advancedgarage#135]
Hey, I install it correct but i cannot see any blip or circles to spawn or despawn cars. any help please?

**Comment by N1ma6** [comment]
I got the same issue

**Comment by N1ma6** [comment]
you can install an earlier version, it worked for me

**Comment by HumanTree92** [comment]
Make sure you are using the newest es_extended and you are not using essentialmode.

**Comment by overdam** [comment]
> Make sure you are using the newest es_extended and you are not using essentialmode.

But i need esssntialmode for something else to work

**Comment by HumanTree92** [comment]
Let me guess ur using essentialmode and es_admin2. Are u using the latest es_extended or what.

**Comment by HumanTree92** [comment]
Make sure you edit the config to your liking. By default everything is set to false meaning nothing will work. So say you want to use the Car garage you need to set Config.UseCarGarages = true and say if you want to use blips you also need to set Config.UseCarBlips = true
