### ISSUE TITLE
note

### ISSUE THREAD

**Issue by hamood192244** [HumanTree92/esx_advancedgarage#136]
**Describe the bug**
why when i go to pound and get my car from there its ok and good.
but when i respawn it again in the same time , the first one do not disappear
you can do this

**Questions**
Are you using the Latest es_extended:  yes
Who is your Hosting Provider: my pc
Linux or Windows: Windows
OneSync (Yes or No): yes

**Comment by HumanTree92** [comment]
https://github.com/HumanTree92/esx_advancedgarage/wiki/Bugs,-Questions,-Etc.
