### ISSUE TITLE
can't see neither blips nor markers for garages

### ISSUE THREAD

**Issue by daZepelin** [HumanTree92/esx_advancedgarage#137]
**Describe the bug**
_A clear and concise description of what the bug is._
can't see neither blips nor markers for garages, resource does start and no errors printed, /getgarages command is registered on server. 

**Questions**
_Are you using the Latest es_extended:_  1.2.0
_Who is your Hosting Provider:_ zaphosting
_Linux or Windows:_  linux
_OneSync (Yes or No):_ no

**Additional context**
_Add any other context about the problem here._
Tried reinstalling the resource multiple times as well as esx

**Comment by HumanTree92** [comment]
https://github.com/HumanTree92/esx_advancedgarage/issues/135
