### ISSUE TITLE
Question- how to remove pounds

### ISSUE THREAD

**Issue by mifsopo** [HumanTree92/esx_advancedgarage#14]
this is just a simple question as you closed my last one, if i disable the vehicle pounds and decide to use a different impound system, when i player logs without storing vehicle will it auto go back to garage or will that cause an issue in the cars?

**Comment by HumanTree92** [comment]
You could have commented on ur other issue. But it should work. In most cases if a player logs out without storing the Vehicle there is a small chance that their vehicle will still be there but in most cases the Vehicle will despawn & it won't go back to the garage. So u will need a Impound Script if u want players to able to get their vehicles back.
