### ISSUE TITLE
script error on install

### ISSUE THREAD

**Issue by Ashember** [HumanTree92/esx_advancedgarage#140]
**Describe the bug**
When installing there is an error out the shoot, which I could not find in the wiki.  

"Error loading script server/main.lua in resources esx_advancedgarage: @esx_advancedgarage/server/main.lua:26 attempted to call a nil value (field 'RegisterCommand') stack traceback: @esx_advancedgarage/server/main.lua:26 in chunk
Failed to load script server/main.lua"

**Questions**
Are you using the Latest es_extended: yes
Who is your Hosting Provider: dedicated Sever
Linux or Windows: Windows Server
OneSync (Yes or No): no

**Additional context**
Upgrading from the old esx_advancedgarage, added this to the bottom of the , did the sql.
<img width="664" alt="Screenshot_4" src="https://user-images.githubusercontent.com/23489428/80628717-cc094400-8a1f-11ea-8407-cfcbbbc4ac6b.png">

**Comment by HumanTree92** [comment]
Already has been answered. You are not using the latest ESX or you have not updated your FiveM or you are using Essentialmode. If your using essentialmode your shit out of luck as essentialmode is trash. If your are not using Essentialmode and your are using the latest ESX before it was taken down & you have updated FiveM then simply set Config.UseCommand = false

**Comment by HumanTree92** [comment]
The command doesn't really need to be used so long as you set this up with esx_property. You can find out how to set it up via the wiki
