### ISSUE TITLE
DONT SAVE CARS

### ISSUE THREAD

**Issue by cold-cat** [HumanTree92/esx_advancedgarage#142]
**Describe the bug**
when i store my vehicle in garage after that i wnat to bring it back but he says: you dont own any car!

**Questions**
Are you using Essentialmode: no
Are you using the Latest es_extended: yes
Linux or Windows: windows
OneSync (Yes or No): yes

please help this is a big issue

**Comment by HumanTree92** [comment]
Your blocked and dumb. Read the wiki this has been answered 100s of times.
