### ISSUE TITLE
The garage menu does not show any cars

### ISSUE THREAD

**Issue by Nevos08** [HumanTree92/esx_advancedgarage#144]
**Describe the bug**
The garage menu does not show any cars

**Questions**
Have you looked at the Wiki on my Website: no
Are you using Essentialmode: yes
Are you using the Latest es_extended: Im using extendedmode
Who is your Hosting Provider: kernelhost.de
Linux or Windows: linux
OneSync (Yes or No): yes

**Additional context**

**Comment by HumanTree92** [comment]
Ur dumb. Maybe you should read the Readme where it states Check the Closed Topics & Wiki before opening an issue to see if your issue has already been Answered.

    Failure to due the above will result in Topic being Deleted & you being Blocked. IDGAF if i block you. It doesn't hurt me.

This will be deleted soon.
