### ISSUE TITLE
Not able to store vehicles

### ISSUE THREAD

**Issue by Death-Avenger** [HumanTree92/esx_advancedgarage#15]
So I am not seeing any errors on the server. I installed the file within resources folder and added the start command. The SQL tables already existed with the correct Plate field as the key. 

While testing I was not able to store a newly purchased vehicle. I verified that the vehicle did get registered to the character. I checked under stored vehicles and it did not get entered here. I do not know why the status would not be updated to stored? 

Any assistance you can provide would be great.

**Comment by Death-Avenger** [comment]
Resolved. Had to update the owned vehicles table and then modify the Main.lua file as indicated in other closed support issues.

**Comment by HumanTree92** [comment]
@Death-Avenger Do u remember which support issue it was so i can possibly put in a fix so no one has to go through that.

**Comment by Death-Avenger** [comment]
#7
I did the following and it resolved it:
1. I updated the server main.lua
function ParkVehicles()
MySQL.Async.execute('UPDATE owned_vehicles SET stored = true WHERE stored = @stored', {
['@stored'] = false
}, function (rowsChanged)
if rowsChanged > 0 then
print(('esx_advancedgarage: %s vehicle(s) have been stored!'):format(rowsChanged))
end
end)
end
2. I updated the DB table with:
![image](https://user-images.githubusercontent.com/47287295/55048244-bea3ae00-5004-11e9-9a76-0f0679dd719d.png)
