### ISSUE TITLE
Cars not spawning in.

### ISSUE THREAD

**Issue by willbarra4** [HumanTree92/esx_advancedgarage#154]
**Describe the bug | A Clear & Concise Description of Bug**
Ok, so the cars are not spawning it from the garage. but i know the problem. but i dont want to change the sql database  
![image](https://user-images.githubusercontent.com/60571731/83362292-0b60e280-a388-11ea-816e-bc9f3b269d7a.png) - the problem is the job. when its null. it doesnt work. and it automatically sets as null. can you send me an updated file that doe sit automatically

**Questions**
Have you looked through the Closed Topics?: yes. that made me change the null to civ.
Have you looked through the Wiki?:  yes.
Are you using Essentialmode?: yep.
Are you using es_extended (If yes what Version)?:  V1 - final
Are you using OneSync?: no.
Linux or Windows?: windows

**Comment by HumanTree92** [comment]
Why don't you just edit the job column and change the default value from NULL to civ

**Comment by willbarra4** [comment]
im new to this sort of. What should i edit in the script?

**Comment by HumanTree92** [comment]
If what the easiest method just edit the database. But as far as the other method it depends on what vehicle shop script u use.
