### ISSUE TITLE
No script guid for vehicle - error

### ISSUE THREAD

**Issue by FuryFight3r** [HumanTree92/esx_advancedgarage#155]
**Describe the bug | A Clear & Concise Description of Bug**
![Screenshot_4](https://user-images.githubusercontent.com/44615800/83521180-367f3980-a522-11ea-936f-255be93fb3c7.png)
Receiving the above errors after purchasing a custom addon vehicle using esx_advancedvehicleshop and attempting to store in the garage, it does however delete the vehicle, just doesnt store the vehicle, essentially destroying the vehicle with no way to retrieve it.

Please let me know if it is me that is doing something wrong, or if I have yet to setup something or if its a genuine bug/error. Thanks :)

**Questions**
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Couldnt find wiki with link provided.
Are you using Essentialmode?: Yes
Are you using es_extended (If yes what Version)?: Yes Latest V1
Are you using OneSync?: No
Linux or Windows?: Windows 10 x64

**Comment by HumanTree92** [comment]
There errors you have provided are not from this Script. The errors you have provided are something that has to do with FiveM itself.

**Comment by FuryFight3r** [comment]
Thanks for the reply HumanTree, would there be anyway of fixing this? Or is that up to fivem devs to patch?

**Comment by HumanTree92** [comment]
Are you using Realistic Vehicle Failure. If so i have heard that will cause it as well. Its not really an error. I've seen this show up for a lot of servers so its nothing to worry about.
