### ISSUE TITLE
How can I add more garages?

### ISSUE THREAD

**Issue by Dikidorus007** [HumanTree92/esx_advancedgarage#156]
**Describe the bug | A Clear & Concise Description of Bug**
Can someone explain to me how I can add more garages on the map?

**Questions**
Have you looked through the Closed Topics?:  Yes
Have you looked through the Wiki?:  Yes
Are you using Essentialmode?:  Yes
Are you using es_extended (If yes what Version)?:  Yes V1 final
Are you using OneSync?: Yes
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
If your wanting to make more car garages for example you would just copy the one above and change the Los_Santos to Custom_Loc1

**Comment by Dikidorus007** [comment]
Hi again, It works perfectly now thanks! :D
