### ISSUE TITLE
garage don't show vehicles and a strange error

### ISSUE THREAD

**Issue by OuDayas** [HumanTree92/esx_advancedgarage#157]
**Describe the bug | A Clear & Concise Description of Bug**
I've installed the script, everything work but except for take vehicles from garege.
when the server start after the script is started in the game console i can see that error
SCRIPT ERROR: @esx_advancedgarage/client/main.lua:26: attempot to aindex a nil value (global 'ESX')
and the server console say
[MariaDB:10.4.11.MariaDB] [Slow Query Warning] [esx_advancedgarage] [975ms] UPDATE owned_vehicles SET 'stored' = true WHERE 'stored' = false
(but it work)
the question is, why the console give me those errors and why if I try to store a vehicle in a garage, the garage didn't show me nothing?

**Questions**
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using Essentialmode?: Yes 6.4.2
Are you using es_extended (If yes what Version)?: Yes, lasst
Are you using OneSync?: no
Linux or Windows?: windows

**Comment by HumanTree92** [comment]
Are you self hosting or on a Dedicated Server?

The Slow Query Warning isn't really an error. It also depends on how many vehicles you have in your owned_vehicles. As for the client error for line 26 make sure the garage system is after esx_properties. 

Not sure what you mean by "why if I try to store a vehicle in a garage, the garage didn't show me nothing?"

**Comment by MikZz** [comment]
I am having the same problem, on the game console give me this error when I try to see the cars I have in the garage (do not store any) and the same thing appears on the server console on the database and I am on localhost
[Print](http://prntscr.com/t0u3za)

**Comment by HumanTree92** [comment]
1. As for `slow query warnings` i can't fix those. Rent a FiveM Server or Dedicated Box. 
2. Missing `global ESX` It can be solved by upgrading to ESX V1 Final or using Extended Mode.
@MikZz Not my script. Whoever made the script called `garagens` you need to contact them.

**Comment by MikZz** [comment]
the script is the same, just changed the folder name to translate my language

**Comment by HumanTree92** [comment]
Well don't. If u change the name of the folder I won't help. The name has to be esx_advancedgarage.

**Comment by HumanTree92** [comment]
If u want to use ur own name then you will have to edit the entire script to use the name u want. But even then I won't help with errors.
