### ISSUE TITLE
Saving car plate error 

### ISSUE THREAD

**Issue by Patrickstek121** [HumanTree92/esx_advancedgarage#16]
![image](https://user-images.githubusercontent.com/16652731/55022956-096cf800-4ffc-11e9-98a9-14a6f778bc59.png)

i get this error when im placing the car.

**Comment by Heady20006** [comment]
try to use `stored`   in your where clause in server/main.lua

**Comment by Patrickstek121** [comment]
fixed thanks

**Comment by HumanTree92** [comment]
Yeah i will be pushing an update tonight that will fix that.
