### ISSUE TITLE
Cars not going to impound

### ISSUE THREAD

**Issue by LlamaPalooza89** [HumanTree92/esx_advancedgarage#160]
**Describe the bug | A Clear & Concise Description of Bug**

When I take a car out of my garage and leave it out, it stills says it's in the garage when it should be at the pound. Does the same when I impound a car using the police or mechanic menu.

**Questions**
Have you looked through the Closed Topics?:  YES
Have you looked through the Wiki?: YES
Are you using Essentialmode?: NO
Are you using es_extended (If yes what Version)?: newest
Are you using OneSync?: no
Linux or Windows?: WIn64

**Comment by HumanTree92** [comment]
Make sure your using the sql provided. I have not had this issue at all. Also if you have any client or server side errors it would help figuring out what is going on.

**Comment by HumanTree92** [comment]
Closing due to no comments back. If having problems please re-open.

**Comment by lilwill69** [comment]
i have the same problem and i am using the sql you provided. pls help
