### ISSUE TITLE
What mean the "Heading" value?

### ISSUE THREAD

**Issue by andresf484** [HumanTree92/esx_advancedgarage#161]
**Describe the bug | A Clear & Concise Description of Bug**

Hi,
I am setting up a new garage / deposit, but don't understand what the "Heading" value means.
Is it a coordinate or is it an x-y-z position on the map? or how to know what value should I place, in a new garage / deposit?

an example of the code that I have modified:

![attach1](https://user-images.githubusercontent.com/62083763/84582092-187cc900-adad-11ea-88c5-99bdbb40cdfd.png)

Config.CarPounds = {
	-- Los_Santos = {
		-- Marker = vector3(408.61, -1625.47, 28.29),
		-- Spawner = vector3(405.64, -1643.4, 27.61),point
		-- Heading = 229.54
	-- },
	Los_Santos = {
		Marker = vector3(260.19, -772.39, 30.80), -- blue point
		Spawner = vector3(237.80, -777.19, 30.59), -- spawn location of blue 
		Heading = 229.54 -- I don't understand this
	},	

Result:

![attach2](https://user-images.githubusercontent.com/62083763/84581804-aacf9d80-adaa-11ea-92a0-ea5ae2034e47.png)

Thanks in advance

**Questions**
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using Essentialmode?: yes
Are you using es_extended (If yes what Version)?: es_extended v1 final
Are you using OneSync?: yes 
Linux or Windows?: linux

**Comment by HumanTree92** [comment]
Heading is the direction your looking at.  For example this script [here](https://forum.cfx.re/t/show-coords-and-heading-updated-23-09/45566?__cf_chl_captcha_tk__=2d2a153d1505d9604240888400a55d9f854b0457-1592097110-0-AQlFXH8PlIMm2lxgh92rhBMz4im9pArQXnxGAI3vzIIVb9QkIzsgG5P_FfkCHL-mE4biauk2boPmnznEM_k-R3z-JKn_ZIOOJ2HDXGWXIDmtZQB8tKueP16QGyIbn3Sp8kQi8zmcPBtL1bGiAqxj7e653LHpQF0qdMS3rIghotTA8wV7K_3rtKJkvNyK1Qal-eKKZCVJoGQPxUVM27UlExGHXF7mwQ8uGpN4OJzzPv4uHNl8XuxNd91MJsk7eRRyNtm3iqRyZI3ncNL7Ge9T_uuzphIZgUa7DgX-jLG8J7Rf_5dkgXKncN9sLtEAv4Bv5X7W-zcrd8sMjtJi_eweNI8Oy1dGWgW972rG5UKcVchOoOWJvIubZFR5lXlzIoXP3hSawNuml0GhkHYbCoQzYJvSJOJAVDX4-ZIWBSRHtegS-J5xGlZ5eL5On5R2NXjv2ARCF2ExtQZF6ciGZySZWaKFVP6RwI7-hEvnTVX2V8y7olpMAQUgPbsgZbGZTRZ7uKjSfNqgKNSbRJPVGCzCnLwx1T2YPFpiLJ2FrCIVW6Jvd6i4QYHB8DOoGjRuo5ymc6AWFVYpiHzwgXOVJousN06ZaejsNdgz1NDLeZDs0Qay) shows the heading.

**Comment by andresf484** [comment]
> Heading is the direction your looking at. For example this script [here](https://forum.cfx.re/t/show-coords-and-heading-updated-23-09/45566?__cf_chl_captcha_tk__=2d2a153d1505d9604240888400a55d9f854b0457-1592097110-0-AQlFXH8PlIMm2lxgh92rhBMz4im9pArQXnxGAI3vzIIVb9QkIzsgG5P_FfkCHL-mE4biauk2boPmnznEM_k-R3z-JKn_ZIOOJ2HDXGWXIDmtZQB8tKueP16QGyIbn3Sp8kQi8zmcPBtL1bGiAqxj7e653LHpQF0qdMS3rIghotTA8wV7K_3rtKJkvNyK1Qal-eKKZCVJoGQPxUVM27UlExGHXF7mwQ8uGpN4OJzzPv4uHNl8XuxNd91MJsk7eRRyNtm3iqRyZI3ncNL7Ge9T_uuzphIZgUa7DgX-jLG8J7Rf_5dkgXKncN9sLtEAv4Bv5X7W-zcrd8sMjtJi_eweNI8Oy1dGWgW972rG5UKcVchOoOWJvIubZFR5lXlzIoXP3hSawNuml0GhkHYbCoQzYJvSJOJAVDX4-ZIWBSRHtegS-J5xGlZ5eL5On5R2NXjv2ARCF2ExtQZF6ciGZySZWaKFVP6RwI7-hEvnTVX2V8y7olpMAQUgPbsgZbGZTRZ7uKjSfNqgKNSbRJPVGCzCnLwx1T2YPFpiLJ2FrCIVW6Jvd6i4QYHB8DOoGjRuo5ymc6AWFVYpiHzwgXOVJousN06ZaejsNdgz1NDLeZDs0Qay) shows the heading.

thanks, this solved my issue
