### ISSUE TITLE
the blue dot of the deposit, remains in the air

### ISSUE THREAD

**Issue by andresf484** [HumanTree92/esx_advancedgarage#162]
**Describe the bug | A Clear & Concise Description of Bug**

Point configuration in the cube park:

	Los_Santos2 = {
		Marker = vector3(260.19, -772.39, 30.80),
		Spawner = vector3(237.80, -777.19, 30.59),
		Heading = 157.84
	},	

this is the issue:

![attach3](https://user-images.githubusercontent.com/62083763/84584095-16733400-adc6-11ea-86a0-04f746912277.png)

**Questions**
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using Essentialmode?: yes
Are you using es_extended (If yes what Version)?: es_extended v1 final 
Are you using OneSync?: yes
Linux or Windows?: linux

**Comment by HumanTree92** [comment]
Change 30.80 to 29.80

**Comment by andresf484** [comment]
> Change 30.80 to 29.80

Thanks a lot.

![image](https://user-images.githubusercontent.com/62083763/84584213-0dcf2d80-adc7-11ea-91c2-1f64633be6dc.png)

I have that fivem server for testing. if you ever need to try something, talk to me. :D
