### ISSUE TITLE
Unable to retrieve stored vehicle

### ISSUE THREAD

**Issue by ollie47358** [HumanTree92/esx_advancedgarage#164]
**Describe the bug | A Clear & Concise Description of Bug**
My job is set to "ambulance", grade 3 in the SQL database.
I am able to purchase a vehicle, modify it and then store the vehicle. However, when I come to take that vehicle out again I am told I have no vehicles. It is looking for the following in the database:
SELECT * FROM owned_vehicles WHERE owner = ? AND Type = ? AND job = ? : ["LICENCE","car","civ"]
Currently, job is "null" rather than "civ". I'm wondering if this is something I need to adjust somewhere in your config, or look at my other addons?

**Questions**
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using Essentialmode?: Yes
Are you using es_extended (If yes what Version)?: Latest
Are you using OneSync?: No
Linux or Windows?: Linux

**Comment by HumanTree92** [comment]
No you didn't look through the Closed Topics or Wiki. B/c if you did you would find your answer. If your Job is Ambulance then you can only pull ambulances from the ambulance garage. You would also learn that job must be civ & not NULL. Well have fun being blocked with your fake account that you made b/c you knew you would get blocked.
