### ISSUE TITLE
Script started but nothing happend.

### ISSUE THREAD

**Issue by Arsalan0098** [HumanTree92/esx_advancedgarage#165]
**Describe the bug | A Clear & Concise Description of Bug**
Hello, first of all i wanted to thank you for your great job. its really cool, i used this script many times on many servers and working fine, but this time i buy a new vps and try to start a new server and add your scripts but nothing happend after starting it, i go to the parking places, no blips on the map, and nothing on the locations.
This is my Resources :
`
start mysql-async
start es_extended

start esx_menu_default
start esx_menu_list
start esx_menu_dialog
start Loading_Screen

start skinchanger
start esx_skin
start cron
start esx_addonaccount
start esx_society
start esx_billing
start esx_addoninventory
start esx_datastore
start esx_service
start esx_license
start esx_identity
start esx_basicneeds
start esx_optionalneeds
start esx_dmvschool
start esx_licenseshop
start idcard
start esx_advancedvehicleshop
start esx_advancedgarage

start instance
start mapbugfix
start blips
start esx_simpletp

start esx_addons_gcphone
start gcphone
start postal_map
start gui

#start esx_voice
start esx_status
start esx_accessories
start esx_cruisecontrol
start esx_sit
start new_banking
start LegacyFuel
start SimpleCarHUD
start seatshuf
start No-NPC
start RPChat
start NoDot

start esx_vehicleshop
start esx_clotheshop
start esx_barbershop
start esx_property
#start esx_garage
start svehiclelocks

start esx_inventoryhud
start esx_inventoryhud_glovebox
start esx_inventoryhud_trunk

start esx_ambulancejob
start esx_policejob
start esx_taxijob
start esx_mechanicjob
start esx_jobs
start esx_joblisting
start esx_drugs

start vMenu`
[Screen Shot](https://imgur.com/MvAnlcx)

i also need to add that there is not error in server side when running the script.

**Questions**
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?:  Yes
Are you using Essentialmode?: No
Are you using es_extended (If yes what Version)?: https://github.com/ESX-Org/es_extended/tree/v1-final
Are you using OneSync?:  No
Linux or Windows?: Windows Server 2012

**Comment by HumanTree92** [comment]
Any Console errors. Not much to go on.

**Comment by Arsalan0098** [comment]
> Any Console errors. Not much to go on.

no Console error... everything works fine but nothing happend on server + if i change the Config.UseCommand = false to true, when i type /get   i can see the command is there, but still nothing on the server

**Comment by HumanTree92** [comment]
Make sure you edit the config.lua by default everything is turned off. Example line 53 `Config.UseCarGarages = false`

**Comment by Arsalan0098** [comment]
> Make sure you edit the config.lua by default everything is turned off. Example line 53 `Config.UseCarGarages = false`

i dont belive my friend turned it on :-( i tried everything.... thanks man its working now
