### ISSUE TITLE
Getting saved Vehicle Health on Engine,Body,Tank while spawing car doesnt work on certain vehicleClass.

### ISSUE THREAD

**Issue by yomanmen** [HumanTree92/esx_advancedgarage#166]
**Describe the bug | A Clear & Concise Description of Bug**
Getting saved Vehicle Health on Engine,Body,Tank while spawing car doesnt work for certain vehicleClass (vanilla cars) I tested and didnt work on 
COMPACT ,SPORT_CLASSIC,VANS,OFF ROAD . On rest classes ex SUPER or SPORTS it works fine i can get my saved health points recovered onvehicle spawn!

**Questions**
Have you looked through the Closed Topics?:  Yes i didnt find anything related!

Have you looked through the Wiki?: Yes i searched everything es_extended etc i cant understand what is happening!

Are you using Essentialmode?: No

Are you using es_extended (If yes what Version)?: Yes ( 1.3.0 i have edited some for personal use (inventory things) but nothing related to car spawning)

Are you using OneSync?: yes but limited 32 slots free

Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
I'm not quite sure what ur issue is. Kinda confused. Like what isn't working.

**Comment by yomanmen** [comment]
Sorry for my english its not my native language.. So... When im storing a car in garage for example Tyrus car which class is Super.
When i get it out (spawning) it saves everything like it should damage on engine body etc. and when i spawn the car it is damaged like it should!
 
But! When im saving a Blista it saves on database health points but when im spawning the car it goes back to 1000.0 on all 3 health points! (It is saving everyhting visual mods etc)

**Comment by HumanTree92** [comment]
Ur not supposed to be able to store a damaged vehicle. It's supposed to heal the vehicle when pulling it out.

**Comment by yomanmen** [comment]
Hmmm.. Yes..Im sorry... i forgot to mention that i edited your code part where it makes you pay money to fix the car because i wanted it to store it damaged..I guess your mod doesnt support this feature thats why i got these issues ?

**Comment by HumanTree92** [comment]
Yes. When I tried it that way I had issues.

**Comment by yomanmen** [comment]
I see i hitted the same wall as you i guess sorry for the issue i submited and thanks for fast answering!

**Comment by HumanTree92** [comment]
By default u have to pay to fix ur vehicle. I'm not sure what would be causing it to not work. Original I wanted it the way u chose but too many bugs that I couldn't fix.
