### ISSUE TITLE
client/main.lua:33 script error

### ISSUE THREAD

**Issue by raidzion** [HumanTree92/esx_advancedgarage#167]
**Describe the Bug | A Clear & Concise Description of Bug**
I get an SCRIPT ERROR on the line commented on the title but the garage works great, i want know if its ok to continue using it or maybe can create a problem later.

line33:`	 ESX.PlayerData = xPlayer`
https://i.imgur.com/RLsr5aI.png(url)

**Questions**
Have you looked through the Closed Topics?:  Yes
Have you looked through the Wiki?: Yes
What Version of es_extended are you using?: 2.0.1
Are you using a Pre-Installed ESX?: No
Are you using Essentialmode?: Yes
Are you using OneSync?: Yes
Linux or Windows?:  Windows

**Comment by HumanTree92** [comment]
No esx_ resource will 100% work with any ESX V2. Thats why i state to use V1 Final or EXm

**Comment by raidzion** [comment]
You recommend me to continue using it or change the garage?, because i am properly coding more resources to the server.

**Comment by HumanTree92** [comment]
If u want to recode it to work then I can. The script is meant for V1 final. I am waiting for ESX V2 to be more stable. 

Now if u recode the script I gladly ask that u not release it as ur own.

**Comment by raidzion** [comment]
Ok thanks you for the answer i will see if can solve it and tell you, else i think remove it is better.

**Comment by HumanTree92** [comment]
Remove what? If u fix it and send it to me I can compare it to the one I am working on and then I will release it with this. Pretty much my goal will be to release a V1 and V2 all in the same pack.

**Comment by raidzion** [comment]
I mean replace with other to not get errors when lauching but i will test whats the problem, because it works well but threw that error

**Comment by HumanTree92** [comment]
That error is thrown bc it can't find esx. And since the whole es_extended got rewritten in V2 is why it can't find the global esx.

**Comment by HumanTree92** [comment]
My goal is to implement all my scripts for V2 as modules just like they have it for skin and etc.
