### ISSUE TITLE
job = 0

### ISSUE THREAD

**Issue by xrtw** [HumanTree92/esx_advancedgarage#168]
im updating this plugin, but all my cars are 0 value, how to make all 0 values into civ? 
job column

**Comment by xrtw** [comment]
https://gyazo.com/0b21425249a7e26650384470713711c4
https://gyazo.com/bfe3747c7573bad2fa464a33bd61d51e

**Comment by HumanTree92** [comment]
Your answer is in the Readme & Wiki.

**Comment by HumanTree92** [comment]
If you already have vehicles with no value you must double click and type civ into each one. There are other methods but you can look those up on google

**Comment by xrtw** [comment]
ok thanks, have ~5k tables..

**Comment by HumanTree92** [comment]
I would look that up on google. [Here is one example](https://stackoverflow.com/questions/47327051/mysql-how-to-change-value-in-column) but using [google you will find many answers](https://www.google.com/search?safe=off&sxsrf=ALeKk00DksQRr6I9RVlcxE2XIOvHCT31ZQ%3A1594387730883&ei=Em0IX8jANdu0tQbPpqCQDQ&q=phpmyadmin+change+column+value&oq=phpmyadmin+change+column+value&gs_lcp=CgZwc3ktYWIQAzIHCAAQRxCwAzIHCAAQRxCwAzIHCAAQRxCwAzIHCAAQRxCwAzIHCAAQRxCwAzIHCAAQRxCwAzIHCAAQRxCwAzIHCAAQRxCwA1AAWABg6yRoAXAAeACAAQCIAQCSAQCYAQCqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwjIkdWS5cLqAhVbWs0KHU8TCNIQ4dUDCAs&uact=5)

**Comment by xrtw** [comment]
great, thanks, it worked `UPDATE `owned_vehicles` SET `job` = 'civ' WHERE `job` = '';`
