### ISSUE TITLE
ESX_advancedgarage - German Translation

### ISSUE THREAD

**Issue by SBTunly** [HumanTree92/esx_advancedgarage#169]
**Hello there :)**

I have translated this plugin into German:

https://forum.cfx.re/t/release-esx-esx-advancedgarage-german-translation/1430265

Is it ok ?

**Questions**
Have you looked through the Closed Topics?: 
Have you looked through the Wiki?: 
What Version of es_extended are you using?: 
Are you using a Pre-Installed ESX?: 
Are you using Essentialmode?: 
Are you using OneSync?: 
Linux or Windows?:

**Comment by HumanTree92** [comment]
No its not okay. All you should have done was a PR

**Comment by HumanTree92** [comment]
Just downloaded the file & im uploading it soon.
