### ISSUE TITLE
No cars at impound

### ISSUE THREAD

**Issue by lilwill69** [HumanTree92/esx_advancedgarage#170]
**Describe the Bug | A Clear & Concise Description of Bug**
If i blow up my car or it breaks i can't find it at the impound. (and that is for everyone) 
But when i restart the server the cars is at the garage.
F8 looks like this = https://gyazo.com/893b62fb1f67e7c2f4058fd45ebeff3d
And i have used the sql you provided.

**Questions**
Have you looked through the Closed Topics?: Yes but i didn't get much out of that
Have you looked through the Wiki?: Yes
What Version of es_extended are you using?: Latest 
Are you using a Pre-Installed ESX?: Yes
Are you using Essentialmode?: Yes
Are you using OneSync?: No
Linux or Windows?: Linux

**Comment by HumanTree92** [comment]
What pre-installed ESX are you using?

**Comment by lilwill69** [comment]
I use zap so pretty much everything
https://github.com/zap-fivem/esx

**Comment by HumanTree92** [comment]
Oof. Yeah Zap hosting is way out of date on their scripts.

But update the script to the latest b/c the error on line 529 points to https://github.com/HumanTree92/esx_advancedgarage/blob/master/client/main.lua#L529 which doesn't make any sense. Also you are not using the latest es_extended b/c there is no line 1316 as you can see here https://github.com/esx-framework/es_extended/blob/v1-final/client/functions.lua

Most if not all of Zaps scripts are out of date. All my scripts are updated to support ESX V1 Final or EXM Latest. I recommend downloading the scripts yourself & installing them. The only pre-installed ESX i can recommend is Ribsosay as its the only pre-installed ESX that stays up to date. But Ribsosay is a Paid pre-install of ESX.

**Comment by lilwill69** [comment]
Thanks!!!
