### ISSUE TITLE
Duplicate Vehicle Via Garage Glitch

### ISSUE THREAD

**Issue by YInfeRnal** [HumanTree92/esx_advancedgarage#171]
**Describe the Bug | A Clear & Concise Description of Bug**
buy a car / seat in Second seat and store vehicle in garage 
the notifaction send your vehicle stored in the garage and your vehicle go to garage but your vehicle still not going to garage and you have it ! you have 1 in garage and 1 and you can dublicate a vehicle

**Questions**
Have you looked through the Closed Topics?: y
Have you looked through the Wiki?: y
What Version of es_extended are you using?: extendedmode
Are you using a Pre-Installed ESX?: no
Are you using Essentialmode?: y
Are you using OneSync?: y
Linux or Windows?: w

**Comment by Kohy7** [comment]
I have same issue, I will store my vehicle and write to me that the vehicle has been saved but will not disappear

**Comment by YInfeRnal** [comment]
any help?

**Comment by HumanTree92** [comment]
Can you explain in detail. Are you in the driver seat or passenger seat?

**Comment by YInfeRnal** [comment]
passenger seat

**Comment by YInfeRnal** [comment]
i send video now

**Comment by HumanTree92** [comment]
No need for a video. I will just add a check to make sure your in the driver seat.

**Comment by YInfeRnal** [comment]
yes thanks 
and do you have any plan to fix impound problem? or any way to fix? thats big problem

**Comment by HumanTree92** [comment]
Which problem is that?

**Comment by YInfeRnal** [comment]
https://filebin.net/48vdqszsxxrr0aa1

**Comment by HumanTree92** [comment]
Ah what do you have set for Config.PoundWait

**Comment by YInfeRnal** [comment]
i do that this just set the time not fix the problem
i see some servers fix the problem
after 1 minues wait player can do that agin and agin and agin...

**Comment by YInfeRnal** [comment]
a way to when someone return his vehicle from impound the player cant do that agin and vehicle return

**Comment by HumanTree92** [comment]
Yeah i have seen a similar script that has fixed the issue but i can't just steal his code as a fix. Currently the PoundWait is my fix until i have time to actually work on scripts.

**Comment by YInfeRnal** [comment]
police and ambulance pound have this problem to

**Comment by YInfeRnal** [comment]
ok i waiting for you to fix the problem 
thanks bro **:small**
:small :small :smal :small 
im waiting

**Comment by YInfeRnal** [comment]
your so so asshole and trash you know that right? trash

**Comment by HumanTree92** [comment]
@YInfeRnal I didn't do nothing to you.
