### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Richards0nd** [HumanTree92/esx_advancedgarage#173]
**Describe the Bug | A Clear & Concise Description of Bug**
My problem is when I try to spawn a car in my garage.
The car is not showing, the console shows that the vehicle model does not exist.
It makes all changes to the database correctly. (In this case, correctly set the vehicle out of the garage)
Also, when I bought the vehicle at the car store, and went to store it, he kikou me saying that I probably had a cheat.
However, when I went to look at the LOG to see if the vehicle hash was different, it was not different, it was correct, there was no reason to kikar me from the server.
I really don't know why this problem is occurring.
I've already checked all the code, and I can't find any problems with it.
In the old version I had, it was working correctly.
I downloaded the new version today, and I modified it as it was before, in this case, without using the garages system for Ambulance and Police

Correction¹: the kikar part of the server I believe has managed to correct the problem.
I identified a small problem in the SQL code in the storeVehicle function
There was an error in the part of the plate.

```
It was like this:
@plate = plate
I put it like this:
plate = @plate
```
So, after the fix¹ I am no longer being server kikado, but I still can't spawn the cars, and I can't store those cars in the garage.
He says I can't keep the vehicles in the garage.
I went to check the hashes of the vehicles, and they are correct, the owner is correct.
Everything is working perfectly in logic, however I don't know what can be the problem.

Video demonstrating everything: https://youtu.be/z-sDx85N9g4

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: yes
Have you looked through the Closed Topics?: Yes, I checked all recently closed topics. None of them have the problem I have.
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using es_extended? If Yes what Version? (Example: 1.2): version 1.2
Are you using Essentialmode?: no
Are you using ExtendedMode?: no
Are you using OneSync?: yes
Linux or Windows?: Linux

**Comment by HumanTree92** [comment]
Try upgrading your es_extended to V1 Finale. es_extended V1.2 is way behind V1 Finale. As you can see V1.2 is at [479 Commits](https://github.com/esx-framework/es_extended/tree/1.2.0) & V1 Finale is at [633 Commits](https://github.com/esx-framework/es_extended/tree/v1-final).

**Comment by Richards0nd** [comment]
Sorry, I was not clear then.
My version is the latest from ESX, other than 2.0.
In this case, I am using the V1 Finale version.

**Comment by HumanTree92** [comment]
Sorry that its been a while. I finally was able to test things out. For some reason i am able to store the vehicle adder without any problems. Not sure what could be causing this issue. 

However the video you provided is super laggy & doesn't provide any help. You also mentioned you made changes to the code which honestly i don't recommend unless you know what your doing. I have seen the mistake for the @plate but it shouldn't matter where its at. I have done the same change as you but still not a single problem.
