### ISSUE TITLE
after new update the previews problems still show some times...

### ISSUE THREAD

**Issue by fucekar** [HumanTree92/esx_advancedgarage#174]
**Describe the Bug | A Clear & Concise Description of Bug**
so impound problem fixed but the garage problem show sometimes
when you park your vehicle in garage (police garage / ambulance garage and ... garage) sometimes not all times this say your vehicle has parked but you still have your vehicle and you can dublicate...
after new update this not fixed yet but impound problem fixed..
thanks

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: y
Have you looked through the Wiki?: y
Are you using a Pre-Installed ESX? If Yes who?: n
Are you using es_extended? If Yes what Version? (Example: 1.2): ,
Are you using Essentialmode?: y
Are you using ExtendedMode?: y
Are you using OneSync?: y
Linux or Windows?: w

**Comment by Djamuras** [comment]
I will push a commit which helped me with this problem in couple hours

**Comment by Djamuras** [comment]
#175 Try this update.
This fix helped me on my server

**Comment by fucekar** [comment]
i have same
