### ISSUE TITLE
retrieve job vehicle impounded when job pound deactivated

### ISSUE THREAD

**Issue by ElBartt** [HumanTree92/esx_advancedgarage#176]
**Describe the Bug | A Clear & Concise Description of Bug**
When using `Config.UseCarGarages = true ` but all other pound/garage to false (police etc). 
If a police car despawn, the car will no longer stored. As there is only "civ" car in pound, there is no way to retrieve the vehicle from anywhere.

It would be good if we could take out job vehicles from the "normal" impound, if the "job" impound is not activated. Or send them back to the garage (set it to stored) when the vehicle despawn.

Except that everything works perfect 👍 

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: NO
Have you looked through the Closed Topics?: YES
Have you looked through the Wiki?: YES
Are you using a Pre-Installed ESX? If Yes who?: NO
Are you using es_extended? If Yes what Version? (Example: 1.2): YES 1.2.0
Are you using Essentialmode?: NO
Are you using ExtendedMode?: NO
Are you using OneSync?: NO
Linux or Windows?: Windows

![image](https://user-images.githubusercontent.com/9247140/89838481-a2f26680-db6b-11ea-919a-5abe35e337d0.png)
![image](https://user-images.githubusercontent.com/9247140/89838499-b271af80-db6b-11ea-8afa-f6ebaccfc9d5.png)
![image](https://user-images.githubusercontent.com/9247140/89838649-0bd9de80-db6c-11ea-9e1c-263ddc7dd329.png)
![image](https://user-images.githubusercontent.com/9247140/89838665-201ddb80-db6c-11ea-99dd-4c28a8963bbb.png)

**Comment by HumanTree92** [comment]
If you want to be able to take out Job Vehicles from the Regular impound you might as well set Config.UseAmbulancePound & Config.UsePolicePound to true. As there is no way to set it so Job Vehicles come out of Regular Impound if lost or destroyed. Thats why there are Separated. 

Also if you want to have Job Vehicles to be returned to the garage just set Config.ParkVehicles to true. You will have to restart the server or script for it to send all vehicles back to garage.

I understand what you are wanting done. But however with the current setup to stop duplicating vehicles its very hard to set it so if a vehicle is lost or destroyed it goes back to the garage. Its kinda pointless to code something like that and its best just to use the impound feature. As for the Job Vehicles & Regular Vehicles to use the same impound is pointless as well.

**Comment by HumanTree92** [comment]
Without this script and instead if your using esx_policejob when a vehicle is taken out, lost, &/or destroyed you can't pull the vehicle out again. You have to wait until the server restarts or you restart the esx_policejob script.

**Comment by ElBartt** [comment]
Ok I understand your point of you, thanks for replying that quick !

**Comment by HumanTree92** [comment]
Not a problem. Have a good day.
