### ISSUE TITLE
garage "is not running"

### ISSUE THREAD

**Issue by PrantsOP** [HumanTree92/esx_advancedgarage#177]
**Describe the Bug | A Clear & Concise Description of Bug**
The garage dooesnt work (there are no blips on the map for the garage)

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: no
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using es_extended? If Yes what Version? (Example: 1.2): yes v1 final
Are you using Essentialmode?: yes the 6.2.2 but i use es_extended db
Are you using ExtendedMode?: no
Are you using OneSync?: no
Linux or Windows?: windows

**Comment by HumanTree92** [comment]
Did you do #4 in the ReadMe? Edit the config.lua before starting the script. By default everything is turned off.

**Comment by PrantsOP** [comment]
Now I have other issue it says "you don't own any car" but I made the SQL correctly :(

**Comment by HumanTree92** [comment]
Send image of ur owned_vehicles

**Comment by SyntaxYT2020** [comment]
Sam issue, Screenshots: 

Ingame: https://prnt.sc/ug5m7u

Database: https://prnt.sc/ug5mml

No errors in the Console or F8 Console

**Comment by HumanTree92** [comment]
@SyntaxYT2020 Ur database is wrong. Ur job table is incorrect. Re-upload my sql fix.

**Comment by HumanTree92** [comment]
Closing issue b/c no reply from op
