### ISSUE TITLE
Vehicle Name says NULL.

### ISSUE THREAD

**Issue by FakeItalianMan** [HumanTree92/esx_advancedgarage#183]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: Nope
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: Nope
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.2
Are you using Essentialmode?: Nope
Are you using ExtendedMode?: Nope
Are you using OneSync?: Yes
Linux or Windows?: Windows

Hello, I have a question most likely only needing a simple answer how do I fix in the garage where it says vehicle name, How do I get that to actually put the vehicle name and not NULL. Thanks.

**Comment by HumanTree92** [comment]
Check the Wiki.
