### ISSUE TITLE
unable to add more garages

### ISSUE THREAD

**Issue by pusseycatmuncher** [HumanTree92/esx_advancedgarage#184]
**Describe the Bug | A Clear & Concise Description of Bug**
i wish to add more custom garages and am not having much luck!

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no but tried to add a new garage to config and also tried to change corods and diddnt work
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: 
Are you using es_extended? If Yes what Version? (Example: 1.2):Yes,  1.1.0
Are you using Essentialmode?: yes
Are you using ExtendedMode?: no
Are you using OneSync?: no
Linux or Windows?: server is linux based

**Comment by HumanTree92** [comment]
Which type of garages. For example of a car garage"
```
	NAME_HERE = {
		Marker = vector3(x, y, z), -- This is the Marker you walk in to
		Spawner = vector3(x, y, z), -- This is where the vehicle will spawn
		Deleter = vector3(x, y, z), -- This is where you go to store the vehicle
		Heading = -- The heading for which direction you want the vehicle to spawn
	},
```
