### ISSUE TITLE
Any fix for max vehicle 36?

### ISSUE THREAD

**Issue by kevintransp** [HumanTree92/esx_advancedgarage#188]
Any know fix for

"There is a Limit on how many Vehicles that can be in each garage. For me it was 36 Vehicles in the Car Garage but after that i couldn't pull anymore out. You can still buy more Boats & Planes if the Car Garage is at 36."

**Comment by HumanTree92** [comment]
This is already a known issue so why create a new issue. I am working on a fix currently however i know of a lot of people that are not going to  like it but idgaf.

**Comment by HumanTree92** [comment]
Also since you didn't follow the Ticket system you have been blocked.
