### ISSUE TITLE
Vehicles Despawn

### ISSUE THREAD

**Issue by KOKOSTAS2001** [HumanTree92/esx_advancedgarage#189]
**Describe the Bug | A Clear & Concise Description of Bug**
Vehicles despawn when i left one car in paleto for example and i disconnect, and if i reconnect again its not there

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  NO
Have you looked through the Closed Topics?: YES
Have you looked through the Wiki?: YES
Are you using a Pre-Installed ESX? If Yes who?: NO
Are you using es_extended? If Yes what Version? (Example: 1.2):  V1 FINAL
Are you using Essentialmode?:  YES
Are you using ExtendedMode?:  YES
Are you using OneSync?:  YES
Linux or Windows?:  WINDOWS

**Comment by HumanTree92** [comment]
Thats not an issue with this script.
