### ISSUE TITLE
Not able to take car out of garage 

### ISSUE THREAD

**Issue by Samantha331** [HumanTree92/esx_advancedgarage#19]
when i put a car in the garage i can't get it out

**Comment by Samantha331** [comment]
it says that i don't own a vehicle

**Comment by HumanTree92** [comment]
Check that you have everything setup correctly with esx_vehicleshop using the new plate system. Send me a picture of your owned_vehicles structure.

**Comment by mrkmav** [comment]
i got the same problem "it says that i don't own a vehicle"

**Comment by Samantha331** [comment]
I'm just confused but i don't have this when i go in to pnpadmin https://imgur.com/OSUi8ya

**Comment by Samantha331** [comment]
@HumanTree92 
![image](https://user-images.githubusercontent.com/49114569/55291716-c9b56000-53af-11e9-972b-5cce29238a95.png)

**Comment by Samantha331** [comment]
there you go

**Comment by HumanTree92** [comment]
The problem is Null. Until i get the time to fix this just edit the job to Default: None | Null: Unchecked
