### ISSUE TITLE
Private Garage Issue

### ISSUE THREAD

**Issue by deputydavis** [HumanTree92/esx_advancedgarage#191]
**Describe the Bug | A Clear & Concise Description of Bug**

The issue that I am having is, we have enabled Config.Pvt to enable Private Garages but the simply do not work. 

We are using esx_properties, confirmed in the database that when a property is purchased it is inputted in the correct places, but the markers for the garages do not show.

There are no errors or issues in F8 console, or server command console. 

Any advice, or direction is greatly appreciated.

Thanks!

Troubleshooting Done:
Located exact coords where markers are supposed to be and teleported to them, no markers.
Removed all purchased properties from the database and remade the purchases with advanced garage running, no markers.

**Comment by deputydavis** [comment]
I also found on your website where to make it work with esx_property, made the changes and I am getting: 
![image](https://user-images.githubusercontent.com/40872235/98844143-e766fa00-2419-11eb-8ea8-0d2a26b5db0c.png)

**Comment by deputydavis** [comment]
this is the edit where I input what was found on the website.

`
function SetPropertyOwned(name, price, rented, owner)
	MySQL.Async.execute('INSERT INTO owned_properties (name, price, rented, owner) VALUES (@name, @price, @rented, @owner)',
	{
		['@name']   = name,
		['@price']  = price,
		['@rented'] = (rented and 1 or 0),
		['@owner']  = owner
	}, function(rowsChanged)
		local xPlayer = ESX.GetPlayerFromIdentifier(owner)

		if xPlayer then
			TriggerClientEvent('esx_property:setPropertyOwned', xPlayer.source, name, true)
			xPlayer.triggerEvent('esx_advancedgarage:getPropertiesC')

			if rented then
				TriggerClientEvent('esx:showNotification', xPlayer.source, _U('rented_for', ESX.Math.GroupDigits(price)))
			else
				TriggerClientEvent('esx:showNotification', xPlayer.source, _U('purchased_for', ESX.Math.GroupDigits(price)))
			end
		end
	end)
end

function RemoveOwnedProperty(name, owner)
	MySQL.Async.execute('DELETE FROM owned_properties WHERE name = @name AND owner = @owner',
	{
		['@name']  = name,
		['@owner'] = owner
	}, function(rowsChanged)
		local xPlayer = ESX.GetPlayerFromIdentifier(owner)

		if xPlayer then
			TriggerClientEvent('esx_property:setPropertyOwned', xPlayer.source, name, false)
			xPlayer.triggerEvent('esx_advancedgarage:getPropertiesC')
			TriggerClientEvent('esx:showNotification', xPlayer.source, _U('made_property'))
		end
	end)
end
`

**Comment by deputydavis** [comment]
I am an airhead, I was able to get the issue fixed but now I have a question.

Under the config you can enable Commands for /getproperties, is there any way to have this done automatically? 

So that people dont have to leave and join back or do the command? 

Thanks again!

**Comment by HumanTree92** [comment]
It is automatically done if you do the code for esx_property. However if you restart the garage script players will have to do /getproperties
