### ISSUE TITLE
broken garage

### ISSUE THREAD

**Issue by anonymonstr** [HumanTree92/esx_advancedgarage#192]
**Describe the Bug | A Clear & Concise Description of Bug**

Every time i store a vehicle bought from PDM into the garage, thats the last time i see it, i got to the green zone and it tells me i dont own a car, i got to the impound, it charges me, but still no car. what am i doing wrong?

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?:  yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using es_extended? If Yes what Version? (Example: 1.2): 
Are you using Essentialmode?: yes
Are you using ExtendedMode?: 
Are you using OneSync?: no
Linux or Windows?: linux

**Comment by HumanTree92** [comment]
please post image of your owned_vehicles structure

**Comment by anonymonstr** [comment]
What file would that be in again? Sorry I’m going on 30 hours wake time 😂

**Comment by anonymonstr** [comment]
![image](https://user-images.githubusercontent.com/74518178/99316349-2226c300-285c-11eb-850f-c64d5db38f75.png)

**Comment by HumanTree92** [comment]
the owned_vehicles structure is the thing in your database

**Comment by anonymonstr** [comment]
sorry, ive slept now :'D 

![image](https://user-images.githubusercontent.com/74518178/99346900-9ded3380-288d-11eb-8365-5cbbe129cca2.png)

**Comment by anonymonstr** [comment]
![image](https://user-images.githubusercontent.com/74518178/99346953-bc532f00-288d-11eb-8346-6d232cb58b6f.png)

**Comment by HumanTree92** [comment]
thats still not the correct image. Take a look at the wiki for help seeing the correct image

**Comment by HumanTree92** [comment]
Re-Open issue once you submit a new comment.
