### ISSUE TITLE
SQL?

### ISSUE THREAD

**Issue by johnsoul777** [HumanTree92/esx_advancedgarage#194]
**Describe the Bug | A Clear & Concise Description of Bug**

No standard SQL file? for installations from 0

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: no
Have you looked through the Wiki?: no
Are you using a Pre-Installed ESX? If Yes who?: extendedmode
Are you using es_extended? If Yes what Version? (Example: 1.2): extendedmode
Are you using Essentialmode?: no
Are you using ExtendedMode?: yes
Are you using OneSync?: yes
Linux or Windows?: windows

**Comment by johnsoul777** [comment]
sorry, i think this are your advanced vehicleshop....

**Comment by HumanTree92** [comment]
This file doesn't have a SQL as with the latest code you should be using esx_advancedvehicleshop which has all the code for this script.
