### ISSUE TITLE
Legacy fuel

### ISSUE THREAD

**Issue by ismaelviac** [HumanTree92/esx_advancedgarage#195]
**Describe the Bug | A Clear & Concise Description of Bug**
LegacyFuel sync dont work, it saves the fuel on database but on spawn vehicle appear with random fuel

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: no
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.2
Are you using Essentialmode?: no
Are you using ExtendedMode?: yes
Are you using OneSync?: yes
Linux or Windows?: linux

**Comment by HumanTree92** [comment]
Did u enable legacy fuel in the config.lua

**Comment by HumanTree92** [comment]
Also did u upload the sql file from esx_advancedvehicleshop.

**Comment by ismaelviac** [comment]
Yes and i see the fuel on database
