### ISSUE TITLE
Error In Console

### ISSUE THREAD

**Issue by bluebear14** [HumanTree92/esx_advancedgarage#2]
![image](https://user-images.githubusercontent.com/47225189/52078547-75cdfc80-2561-11e9-9027-000fd6bcccdc.png)

**Comment by HumanTree92** [comment]
Do you have the store column in owned_vehicles?

**Comment by bluebear14** [comment]
What do you mean?

**Comment by HumanTree92** [comment]
Do you have a column in owned_vehicles called stored or not?

**Comment by bluebear14** [comment]
My apologies.

**Comment by Garik0w** [comment]
The only problem with this process is that when the vehicle is in the deposit you can take it out as many times as you want, that if paying the fee, I think there is a problem with the DontShowPoundCars or something similar, but I can not make it work ...
