### ISSUE TITLE
Garage Issue

### ISSUE THREAD

**Issue by ChrisC1434** [HumanTree92/esx_advancedgarage#201]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: Nope
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: Nope
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.2
Are you using Essentialmode?: Nope
Are you using ExtendedMode?: Nope
Are you using OneSync?: Yes
Linux or Windows?: Linux

Hello I have a question, I have the vehicle names lua all installed I have it as it's own script with all the vehicle names in it, and it works for 98% of the car names, but for some reason it is still showing some cars as NULL any idea on why? Thank you.

**Comment by HumanTree92** [comment]
check the vehicles.meta make sure the info there is correct. For example
`
<modelName>camaross</modelName>
<txdName>camaross</txdName>
<handlingId>CAMAROSS</handlingId>
<gameName>CAMAROSS</gameName>
`
Also vehicle spawn names can't be over a certain amount of characters. Try to keep all vehicle spawn names 10 characters or less.
