### ISSUE TITLE
Remove categories list?

### ISSUE THREAD

**Issue by bizzlebug** [HumanTree92/esx_advancedgarage#202]
**Describe the Bug | A Clear & Concise Description of Bug**

I would like to just list all the vehicles I own without the list of categories, is this possible?

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.2
Are you using Essentialmode?: Yes
Are you using ExtendedMode?: N/A
Are you using OneSync?: No
Linux or Windows?: Windows

![image](https://user-images.githubusercontent.com/77012434/103663185-ba8e1980-4f68-11eb-9d3e-6fdd883d3841.png)

**Comment by HumanTree92** [comment]
You can download the old version from Releases. Or you can wait a few hours for me to update the script to support only showing vehicle categories if you own a vehicle in that category. However due note that if you decide to use the old version that if a player buys more then 35 vehicles it will break the garage for that person & they will not be able to use any garage on the server until the server owner can manually remove some of their vehicles. The new system has the same problem but they can own up to 35 of each categoried vehicle.
