### ISSUE TITLE
Will not let me spawn in a vehicle when I hit "Buy" Police and normal shop.

### ISSUE THREAD

**Issue by ISAFxGhost** [HumanTree92/esx_advancedgarage#204]
**Describe the Bug | A Clear & Concise Description of Bug**
When i hit Buy in the vehicle shop, or police shop it is throwing an error in server panel.

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: ribsosay9
Are you using es_extended? If Yes what Version? (Example: 1.2): yes, unsure of where to find that
Are you using Essentialmode?: yes 6.3.0
Are you using ExtendedMode?: no
Are you using OneSync?: not yet, will be after test server
Linux or Windows?: windows
![image](https://user-images.githubusercontent.com/77240121/104128590-5fb84180-531d-11eb-8b6a-54937df3fce8.png)

![image](https://user-images.githubusercontent.com/77240121/104128604-752d6b80-531d-11eb-8db1-2027afb42238.png)

**Comment by ISAFxGhost** [comment]
Sorry just realized this was for advancedvehicleshop not your garage

**Comment by HumanTree92** [comment]
The show notification error is b/c your not using the ESX V1 Final or ExtendedMode Latest

**Comment by ISAFxGhost** [comment]
Would I be able to update that? Or would it screw up my game? Newer to esx

**Comment by HumanTree92** [comment]
I don't know. You could try to and if it throws errors you can easily revert back.
