### ISSUE TITLE
Error when pressing E to take out police vehicle from garage.

### ISSUE THREAD

**Issue by Kelom78** [HumanTree92/esx_advancedgarage#205]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  NO
Have you looked through the Closed Topics?:  YES
Have you looked through the Wiki?:  YES
Are you using a Pre-Installed ESX? If Yes who?: NO
Are you using es_extended? If Yes what Version? (Example: 1.2):  YES 1.1
Are you using Essentialmode?:  YES
Are you using ExtendedMode?: NO
Are you using OneSync?: YES
Linux or Windows?: Windows

I get this error when I try to take out a vehicle from the police garage. I have esx_advancedgarage, esx_advancedvehicleshop and the esx_licenseshop all running. 

![image](https://user-images.githubusercontent.com/77248246/104138501-b9b01a00-53a4-11eb-8c96-a5892b1ef3b3.png)

**Comment by HumanTree92** [comment]
What does line 387 have. You seem like a few updates behind. Are you using esx_advancedgarage v1 or the master

**Comment by Kelom78** [comment]
I´m using the esx_advancedgarage master

![image](https://user-images.githubusercontent.com/77248246/104213454-946bec00-5436-11eb-91fe-56cc53ea3593.png)

**Comment by Kelom78** [comment]
![image](https://user-images.githubusercontent.com/77248246/104213584-c0876d00-5436-11eb-9766-3388d9ad25a4.png)

**Comment by Kelom78** [comment]
which one should I be using, Downloaded the recources yesterday
