### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PhoenixMods** [HumanTree92/esx_advancedgarage#207]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.1 es_extended
Are you using Essentialmode?: Yes
Are you using ExtendedMode?: No
Are you using OneSync?: Yes
Linux or Windows?: Windows

I get this error code:
https://prnt.sc/wnqhks

**Comment by HumanTree92** [comment]
What did you change. B/c that would only pop up if you changed something. Are you using the Master or the Release of this script.

**Comment by HumanTree92** [comment]
No response in over a month. Closing Issue
