### ISSUE TITLE
I don't see any car in the imprud

### ISSUE THREAD

**Issue by LilEligius** [HumanTree92/esx_advancedgarage#21]
![image](https://user-images.githubusercontent.com/46383847/55994961-80201b80-5cb3-11e9-89bb-8240176eaf22.png)

**Comment by ponduzn** [comment]
I have the same issue, impounded cars doesn't go to impound, goes straight back to garage.. not a huge issue, but annoying..

**Comment by ponduzn** [comment]
I have the same issue, impounded cars doesn't go to impound, goes straight back to garage.. not a huge issue, but annoying..

**Comment by HumanTree92** [comment]
Picture of the structure of owned_vehicles

**Comment by AwakeNz** [comment]
i have the same error when i impound a car does exist on parking ! the same error in F8

**Comment by HumanTree92** [comment]
If your having issues try out some of these other topics that people had worked.
https://github.com/HumanTree92/esx_advancedgarage/issues/22
