### ISSUE TITLE
There is no public garage.

### ISSUE THREAD

**Issue by BaksaBarnus** [HumanTree92/esx_advancedgarage#212]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  No
Have you looked through the Closed Topics?:  Yes
Have you looked through the Wiki?:  yes
Are you using a Pre-Installed ESX? If Yes who?: No 
Are you using es_extended? If Yes what Version? (Example: 1.2):  Yes. I don't know the version
Are you using Essentialmode?:  Yes
Are you using ExtendedMode?:  No
Are you using OneSync?:  Yes
Linux or Windows?:  Windows
There is no public garage on the map.

**Comment by HumanTree92** [comment]
Did u edit the config

**Comment by BaksaBarnus** [comment]
No. I did no nothing, just put it in resources, upload 2 sql files.

**Comment by HumanTree92** [comment]
Well edit the config.lua and read the readme. It tells you what to do.
