### ISSUE TITLE
You don't own any Vehicles for this Garage!

### ISSUE THREAD

**Issue by icozyhoodie** [HumanTree92/esx_advancedgarage#213]
### **Describe the Bug | A Clear & Concise Description of Bug**

**What I did:** 
Deleted the original 'owned_vehicles' table from esx_vehicleshop then I imported the esx_advancedvehicleshop.sql code manually, since importing the sql file wouldn't work for me. No errors in my console or 'F8'

**My Issue:**
I am able to store my vehicles into my public garage but when trying to take my vehicles out of the same garage it gives me this message "You don't own any Vehicles for this Garage!"

**Screenshots:**

Table Structure('owned_vehicles): 
![Table](https://user-images.githubusercontent.com/78667093/107477827-534a2300-6b2d-11eb-86d4-1698a15f26cd.PNG)

In-Game Message:
![Screenshot (9)](https://user-images.githubusercontent.com/78667093/107477803-47f6f780-6b2d-11eb-8943-0ff01d89f219.png)

**Have you made changes to anything in `client/main.lua` or `server/main.lua`?:** No (only to config.lue to show blips and allow use of garage.
**Have you looked through the Closed Topics?:** The ones that related to my specific issue.
**Have you looked through the Wiki?:** I can't find the wiki on the website.
**Are you using a Pre-Installed ESX?** If Yes who?: No
**Are you using es_extended?** If Yes what Version? (Example: 1.2): v1-Final (1.2.0-final)
**Are you using Essentialmode?:** No (disabled)
**Are you using ExtendedMode?:** No
**Are you using OneSync?:** No
**Linux or Windows?:** Windows

**Comment by HumanTree92** [comment]
Post image of your owned_vehicles browse please.

**Comment by icozyhoodie** [comment]
> Post image of your owned_vehicles browse please.

![Table 3](https://user-images.githubusercontent.com/78667093/107495240-ac718100-6b44-11eb-9443-3becc47f3650.PNG)

**Comment by icozyhoodie** [comment]
**Here's what I see in my console if it means anything:**

![Server Console](https://user-images.githubusercontent.com/78667093/107495918-89939c80-6b45-11eb-85d7-3c65af850051.PNG)

**Comment by icozyhoodie** [comment]
**And here's what my server.config includes:**

setr esx_MenuAlign "top-right"

start mapmanager
start chat
start spawnmanager
start sessionmanager
start fivem
start hardcap
start rconlog
start scoreboard
start playernames

### ESSENTIALMODE ###
start async
#start esplugin_mysql
#start essentialmode
start mysql-async
start instance
start cron

### ESX ###

# BASE #
start es_extended
start esx_menu_list
start esx_menu_dialog
start esx_menu_default
start esx_society
start esx_addoninventory
start esx_addonaccount
start esx_billing
start esx_datastore
start esx_license
start esx_identity
start skinchanger
start esx_skin

# JOBS #
start esx_policejob
start esx_property
start esx_ambulancejob

# VEHICLE SHOPS #
# start esx_vehicleshop
start esx_advancedgarage
# start esx_garage
esx_advancedvehicleshop

# OTHER #


### MISC ###
start encore_pointdev
start LegacyFuel

**Comment by icozyhoodie** [comment]
**### And this is what my server.config includes:**

setr esx_MenuAlign "top-right"

start mapmanager
start chat
start spawnmanager
start sessionmanager
start fivem
start hardcap
start rconlog
start scoreboard
start playernames

**### ESSENTIALMODE**
start async
#start esplugin_mysql
#start essentialmode
start mysql-async
start instance
start cron

**### ESX**

**BASE**
start es_extended
start esx_menu_list
start esx_menu_dialog
start esx_menu_default
start esx_society
start esx_addoninventory
start esx_addonaccount
start esx_billing
start esx_datastore
start esx_license
start esx_identity
start skinchanger
start esx_skin

**JOBS**
start esx_policejob
start esx_property
start esx_ambulancejob

**VEHICLESHOPS**
# start esx_vehicleshop
start esx_advancedgarage
# start esx_garage
esx_advancedvehicleshop

**OTHER**


**MISC**
start encore_pointdev
start LegacyFuel

**Comment by HumanTree92** [comment]
The category shouldn't be null. That's the problem. If ur using custom categories u must edit it in esx_advancedgarage

**Comment by icozyhoodie** [comment]
> The category shouldn't be null. That's the problem. If ur using custom categories u must edit it in esx_advancedgarage

I believe this was default after importing sql files.

**Comment by icozyhoodie** [comment]
> The category shouldn't be null. That's the problem. If ur using custom categories u must edit it in esx_advancedgarage

I believe the category was default null upon importing the sql files. Where can I fix this specifically?

**Comment by icozyhoodie** [comment]
![Uploading Vehicles.PNG…]()

**Comment by icozyhoodie** [comment]
'vehicles' table:
![Vehicles](https://user-images.githubusercontent.com/78667093/107498043-23f4df80-6b48-11eb-94c1-79060ef39c41.PNG)

**Comment by icozyhoodie** [comment]
'vehicle_categories' table
![vehicle_categories](https://user-images.githubusercontent.com/78667093/107498348-86e67680-6b48-11eb-9b7f-5cf46143a649.PNG)

**Comment by icozyhoodie** [comment]
vs_cars and vs_car_categories tables have similar category names as well.

**Comment by icozyhoodie** [comment]
So I fixed it to where the category is no longer null, although I still get "You don't own any vehicles for this Garage!" when trying to take out vehicle from public garage. 
![Uploading Table 4.PNG…]()

**Comment by icozyhoodie** [comment]
So I fixed it to where the category is no longer null, although I still get "You don't own any vehicles for this Garage!" when trying to take out vehicle from public garage.
![Table 4](https://user-images.githubusercontent.com/78667093/107559264-b6b96c80-6b90-11eb-9cdc-b4c41d13ced0.PNG)

**Comment by icozyhoodie** [comment]
The wierd thing is I'm able to get the garage menu to open and take out my vehicle after a couple tries and clicking e multiple times to get the menu to open. But I want to be able to just open the garage menu right away after going onto the green circle and clicking "E". Seems I have to click "E" multiple times, really fast and hope for the garage menu to finally open.

**Comment by HumanTree92** [comment]
The garage has Wait timers on them so it can check all owned_vehicles. So you should just have to press E once and wait like 1sec and it should open. But opening & closing the menu multiple times in a short period of time will cause it to load longer since your spam checking the Database for the same thing & it can't keep up.

**Comment by icozyhoodie** [comment]
> The garage has Wait timers on them so it can check all owned_vehicles. So you should just have to press E once and wait like 1sec and it should open. But opening & closing the menu multiple times in a short period of time will cause it to load longer since your spam checking the Database for the same thing & it can't keep up.

You must have a really fast database. The issue occurred even without spamming E.

**Comment by icozyhoodie** [comment]
I was able to fix it by change all Citizen.Wait(250) to Citizen.Wait(850) or Citizen.Wait(1000) for the commands that take the vehicle out of the garage. For anyone else having this problem the code is located via esx_advancedgarage/client/main.lua

**Comment by icozyhoodie** [comment]
> The category shouldn't be null. That's the problem. If ur using custom categories u must edit it in esx_advancedgarage

What file in esx_advancedgarage do I add new categories, I added a new 'electric' category to my database, but I receieve an error in f8.

**Comment by HumanTree92** [comment]
You will have to edit both client & server main.lua files.

**Comment by FreakOutModz** [comment]
I don't use custom categories and having same issue.
