### ISSUE TITLE
No vehicles in garage SQL Error

### ISSUE THREAD

**Issue by jake4612** [HumanTree92/esx_advancedgarage#214]
Have you made changes to anything in client/main.lua or server/main.lua?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: Yes by Zap
Are you using es_extended? If Yes what Version? 1.1.0
Are you using Essentialmode?: Yes
Are you using ExtendedMode?: No
Are you using OneSync?: No
Linux or Windows?: Windows

I am receiving the below error when trying to open the garage in-game.
Seems to be unable to access the SQL server. Is there a way to verify it is using the correct logon details?
Thanks.

[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM owned_vehicles WHERE owner = @owner AND Type = @Type AND job = @job AND category = @category {@category=sports;@job=civ;@Type=car;@owner=steam:110000107a966dc}": Couldn't connect to server

**Comment by HumanTree92** [comment]
Ditch Zaps pre installed ESX. It might be b/c your using SteamID and not RockstarID.

**Comment by jake4612** [comment]
Hmm.

That wouldn't explain why it's not able to connect to SQL server.
Is there a field to specify SQL details in the script?

**Comment by jake4612** [comment]
Alright so seemed to have fixed the error. Nothing in console server/client but still not able to pull out cars.
Any ideas?

**Comment by jake4612** [comment]
Figured out it was adding in columns which aren't there by default.
For example, we use a different car dealer script which has a column such as date of purchase 'date'.

When it exists, it just shows as no vehicles in garage.
How do I add columns and keep the script recognising the cars at the same time?

**Comment by HumanTree92** [comment]
Well the master version of this script can only be used with my esx_advancedvehicleshop. If you don't want to use my esx_advancedvehicleshop then download the one from the releases. But due note i am no longer supporting the one in the releases. As for adding more columns to the owned_vehicles i'm not sure.
