### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by Kraleemil** [HumanTree92/esx_advancedgarage#218]
**Describe the Bug | A Clear & Concise Description of Bug**
I get this error in the consol and you can take the same car out as many times as you want

[ERROR] [MySQL] [esx_advancedgarage] An error happens on MySQL for query "UPDATE owned_vehicles SET stored = false WHERE plate = 'sp 38999'": ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'stored = false WHERE plate = 'sp 38999'' at line 1

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.2
Are you using Essentialmode?: Yes
Are you using ExtendedMode?: Yes
Are you using OneSync?: Legacy 
Linux or Windows?: Windows
And i am using a old verison (https://github.com/benzon/esx_advancedgarage)

**Comment by HumanTree92** [comment]
For one use ESX V1 final just like the readme says. Two ur using an older version which isn't supported anymore. And Three the issue isn't with the script it's something u did. And four ur not even using my version. Topic closed and ur blocked.
