### ISSUE TITLE
Vehicles Not Showing Up In Garage / Impound Not Working

### ISSUE THREAD

**Issue by SerMighty** [HumanTree92/esx_advancedgarage#22]
Vehicles show as Stored in the DB but nothing shows up in-game, also had it where impounding as a Police Officer says complete but the car doesn’t get removed and i could still store it.

![LUA Error](https://user-images.githubusercontent.com/49529556/56424851-d8ee4600-62a9-11e9-8bd7-b3bdab3df932.jpg)

Got the above when accessing a garage, the line 209 is;

![20190419134311_1](https://user-images.githubusercontent.com/49529556/56424824-c1af5880-62a9-11e9-992b-c6db0a084f93.jpg)

**Comment by HumanTree92** [comment]
Picture of the structure for owned_vehicles.

**Comment by SerMighty** [comment]
Fixed using the issue in #8 

It may be worth adding to the install instructions that if people already have the esx_vehicleshop sql they need to change the NULL option or in my case, drop the table and import your fix. 

I derped. appreciate the reply. 

Going to test impounding now once a tester gets on, please do not close

**Comment by SerMighty** [comment]
Update: Impounding my Police car worked

Impounding a civilian vehicle says impound complete however the car remains and the flag in the DB remains as 0, it does go to the impound but of course we have the dupe glitch. It also says if you go and put a previously impounded car in a normal garage, when you take it out, it says its in the impound still. 

Any idea why the car doesn't get removed on impound?

**Comment by HumanTree92** [comment]
That question is for Police or Towtruck Script. The Impound function for those 2 jobs is a 50/50 if it works. /dv works 100% of the time.
