### ISSUE TITLE
Boat store not working & Addon Vehicles not showing up in garage

### ISSUE THREAD

**Issue by Knox623** [HumanTree92/esx_advancedgarage#220]
**Describe the Bug | A Clear & Concise Description of Bug**
It's pretty simple. I have turned on the boat dealer in the config however the circle for it does not appear, even though the blip is there. For the garage it shows up in the database and vanilla vehicles work, but when I store it and go to get it out of the garage it only shows the trucks and vanilla vehicles, not the addon vehicles.
![Capture](https://user-images.githubusercontent.com/63962644/111911527-e300bc80-8a5d-11eb-8e2a-e5aa6490af36.PNG)
![Capture0](https://user-images.githubusercontent.com/63962644/111911528-e300bc80-8a5d-11eb-95a6-b20b36bf7f1f.PNG)

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: Yes, txAdmin/Plume
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.2
Are you using Essentialmode?: No
Are you using ExtendedMode?: Yes
Are you using OneSync?: No
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
For the circle you might have to edit the config.lua for the boat. As for addon vehicles they won't show b/c you are using a custom category called addon which isn't supported by default. It is something you will have to edit yourself to fix.

**Comment by minhgzt** [comment]
@HumanTree92  i start esx_advancegarage already but the garage not show in the map, can you help me

**Comment by Knox623** [comment]
![image](https://user-images.githubusercontent.com/63962644/111928373-4d8c1980-8aab-11eb-8db8-1bdd14595397.png)
Okay, fixing the addon vehicles i'll just put them in the vanilla categories. However with the boat garage im not too sure what else I could change?

**Comment by HumanTree92** [comment]
Scroll down that's not where u change the coords for the marker.

**Comment by HumanTree92** [comment]
Wait is the boat store not working or the boat garage

**Comment by Knox623** [comment]
The boat store wasn't working. The circle is fixed now that i've corrected coords now it says no boats found

**Comment by Knox623** [comment]
![image](https://user-images.githubusercontent.com/63962644/111928786-811b7380-8aac-11eb-972d-2cede8d24794.png)
even though I can quite clearly see them

**Comment by HumanTree92** [comment]
If u restarted the script give it a few mins to reload everything.

**Comment by Knox623** [comment]
ah yeah that was it, cheers 
![image](https://user-images.githubusercontent.com/63962644/111928910-e96a5500-8aac-11eb-827b-84eae4e984e8.png)
