### ISSUE TITLE
Kashacters multiple characters on same acccount has all cars

### ISSUE THREAD

**Issue by dernathan** [HumanTree92/esx_advancedgarage#222]
**Describe the Bug | A Clear & Concise Description of Bug**
Kashacters multiple characters on same acccount has all cars.

logging into another character going to the garage brings up all the cars from other characters on that same account. didnt find a fix yet and no config options. looks like the cars are only getting saved with the license and not char+license in database

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: s-esx v1 full
Are you using es_extended? If Yes what Version? (Example: 1.2): v1 full
Are you using Essentialmode?: no
Are you using ExtendedMode?: no
Are you using OneSync?: yes
Linux or Windows?: windows

**Comment by HumanTree92** [comment]
Not an Issue with this script at all. You will need to setup that crap script to work with this one.
