### ISSUE TITLE
[help] I can't use pound

### ISSUE THREAD

**Issue by MR-SHENXIAO** [HumanTree92/esx_advancedgarage#224]
**Describe the Bug | A Clear & Concise Description of Bug**
I encountered a problem when I was using it. When I could not find the vehicle or the vehicle was damaged, when I went to pound to retrieve the vehicle, it prompted "That Vehicle is Currently out in the World!". What should I do to retrieve my vehicle? My English is not good, I hope it did not bring any errors describing the problem.
![QQ截图20210331205253](https://user-images.githubusercontent.com/81690976/113147401-51fec200-9263-11eb-8e9f-9abd3b29cc72.png)

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  NO
Have you looked through the Closed Topics?:  YES
Have you looked through the Wiki?:  YES
Are you using a Pre-Installed ESX? If Yes who?:  NO
Are you using es_extended? If Yes what Version? (Example: 1.2):  1.2
Are you using Essentialmode?:  NO
Are you using ExtendedMode?:  YES
Are you using OneSync?:  NO
Linux or Windows?:  Windows

**Comment by HumanTree92** [comment]
You will need a /dv script or a job that can impound the vehicle. As technically the vehicle still exists even though it's blown up. U can technically still repair blown up vehicles.
