### ISSUE TITLE
You don't own any vehicle in public Garage

### ISSUE THREAD

**Issue by rhoy1871** [HumanTree92/esx_advancedgarage#225]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  NO
Have you looked through the Closed Topics?: YES
Have you looked through the Wiki?:  YES
Are you using a Pre-Installed ESX? If Yes who?:  NO
Are you using es_extended? If Yes what Version? (Example: 1.2):  1.2
Are you using Essentialmode?:  NO
Are you using ExtendedMode?:  NO
Are you using OneSync?:  NOT YET
Linux or Windows?: LINUX

car is saved in the database but when i try to take it out in garage say i don't own any vehicle. Database structure attached below

![Screenshot 2021-04-14 021407](https://user-images.githubusercontent.com/40468854/114662724-2fd75c00-9cc7-11eb-8476-08db111bdcb3.png)

**Comment by HumanTree92** [comment]
Post image of the browse of the owned_vehicles

**Comment by rhoy1871** [comment]
like this?
![Capture](https://user-images.githubusercontent.com/40468854/114793933-74133c80-9d59-11eb-90eb-2e071c425484.PNG)

**Comment by HumanTree92** [comment]
Yup. You didn't follow the readme. U must be using esx_advancedvehicleshop if you want to use the lastest version. If you want to use esx_vehicleshop go to releases.

**Comment by rhoy1871** [comment]
Ahh ok, I will test it then. Thank you

**Comment by ElNoob83** [comment]
Hello! did that work for you? I'm having exactly the same issue, but I'm using esx_advancedvehicleshop, can you help me?
