### ISSUE TITLE
Garage: garage_no_veh error

### ISSUE THREAD

**Issue by Nox7331** [HumanTree92/esx_advancedgarage#226]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: yes (only changed SetVehicleEngineOn too false.)
Have you looked through the Closed Topics?:  yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using es_extended? If Yes what Version? (Example: 1.2): v1.final
Are you using Essentialmode?: no
Are you using ExtendedMode?: no
Are you using OneSync?: yes
Linux or Windows?: windows

So, after i buy and store it, the garage doenst show me the cars after i restart the game and server. Getting (garage_no_veh)
I don't know why, please help ^^

**Comment by HumanTree92** [comment]
Send image of your owned_vehicles Structure & Browse.

Also make sure if your using the Master Version of the garage that you are also using my esx_advancedvehicleshop.

**Comment by Nox7331** [comment]
I'm using both master versions of esx_advancedgarage and esx_advancedvehicleshop. Will send a picture when i'm home :D

**Comment by Nox7331** [comment]
I attached 2 screenshots, hope it helps.
![Screenshot_1](https://user-images.githubusercontent.com/70815469/115958588-60f62e80-a508-11eb-9ffd-192f332beaf9.png)
![Screenshot_2](https://user-images.githubusercontent.com/70815469/115958590-62275b80-a508-11eb-8df7-f419a598f3a0.png)

**Comment by Nox7331** [comment]
And just in case, i'll attach both scripts.
https://workupload.com/file/NFCMFpUrhJR

**Comment by HumanTree92** [comment]
For your owned_vehicles i see there are 3 vehicles where the owner starts with 1:170 i have never seen a Rockstar ID like that before. The 4th one looks alright.

**Comment by Nox7331** [comment]
Its because of my mutlichar system, on my old server it just worked fine.

**Comment by Nox7331** [comment]
technically, it should work here also.

**Comment by Nox7331** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/70815469/115974656-726a2580-a55e-11eb-8f2e-a2d90fce303a.png)

**Comment by HumanTree92** [comment]
This system uses Rockstar ID not Steam ID. You could try using the Release Version instead of the master version. However i don't think you will be able to use my esx_advancedvehicleshop. Not 100% sure tho.

**Comment by Nox7331** [comment]
Okay, thx. Will try it out.

**Comment by balbuena82** [comment]
It shows you (garage_no_veh) because it is missing in the Spanish language, here everything is corrected, try this 

Locales['es'] = {
	-- Blips
	['blip_garage'] = 'Garaje | Vehículos',
	['blip_garage_private'] = 'Garaje | Privado',
	['blip_pound'] = 'Garaje | Deposito de Vehículos',
	['blip_ambulance_garage'] = 'Garaje | Hospital',
	['blip_ambulance_impound'] = 'Garaje | Deposito Hospital',
	['blip_police_garage'] = 'Garaje | Policía',
	['blip_police_impound'] = 'Garaje | Deposito Policía',
	['blip_mechanic_garage'] = 'Garaje | Mecánicos',
	['blip_mechanic_impound'] = 'Garaje | Deposito Mecánicos',
	
	['blip_garageaircrafts'] = 'Garaje | Aeronaves',
	['blip_garageboats'] = 'Garaje | Barcos',
	['blip_poundaircrafts'] = 'Garaje | Deposito de Aeronaves',
	['blip_poundboats'] = 'Garaje | Deposito de Barcos',

	-- Menus
	['garage_menu'] = 'Elija categoría de vehículo',
	['veh_plate'] = 'Matrícula del Vehículo',
	['veh_name'] = 'Nombre del Vehículo',
	['impound_fee'] = 'Multa',
	['impound_fee_value'] = '$%s',
	['veh_loc'] = 'Localización',
	['veh_loc_unknown'] = 'Desconocido',
	['veh_loc_garage'] = 'En Garaje',
	['veh_loc_impound'] = 'Comprobar deposito',
	['actions'] = 'Acciones',
	['spawn'] = 'Sacar',
	['rename'] = 'Renombrar',
	['veh_rename'] = 'Nombre del Vehículo. | Min: %s / Max: %s',
	['return'] = 'Sacar Vehículo',
	['return_vehicle'] = 'Guardar Vehículo ($%s)',
	['see_mechanic'] = 'Visitar mecánico',
	['damaged_vehicle'] = 'Vehículo dañado',

	-- Categories
	['large_trucks'] = 'Vehículos Industriales',
	['cars'] = 'Coches',
	['helis'] = 'Helicopteros',
	['planes'] = 'Aviones',
	['boats'] = 'Barcos',
	['subs'] = 'Submarinos',
	['box'] = 'Boxed Trucks',
	['haul'] = 'Haulers',
	['other'] = 'Other Trucks',
	['trans'] = 'Transport Trucks',
	['bikes'] = 'Bicicletas',
	['compacts'] = 'Compactos',
	['coupes'] = 'Coupes',
	['motorcycles'] = 'Motos',
	['muscles'] = 'Muscles',
	['offroads'] = 'Off-Roads',
	['sedans'] = 'Sedanes',
	['sports'] = 'Deportivos',
	['sportsclassics'] = 'Deportivos Clasicos',
	['supers'] = 'Supers',
	['suvs'] = 'SUVs',
	['vans'] = 'Furgonetas',

	-- Notifications
	['custom_kick'] = '¡Kickeado por Chetero!',
	['press_to_enter'] = 'Pulsa ~INPUT_PICKUP~ para sacar un vehículo del garaje.',
	['press_to_delete'] = 'Pulsa ~INPUT_PICKUP~ para guardar el vehículo en el garaje.',
	['press_to_impound'] = 'Pulsa ~INPUT_PICKUP~ para acceder al deposito.',
	['garage_no'] = 'No tienes ningún %s!',
	['garage_no_veh'] = '¡No tienes ningún vehículo en este garaje!',
	['impound_no'] = '¡No tienes ningún vehículo en el depósito!',
	['veh_not_here'] = '¡Ese vehículo no está aquí!',
	['veh_out_world'] = '¡Ese vehículo está actualmente en el mundo!',
	['must_ambulance'] = '¡Debe ser trabajador del Hospital para acceder a esto!',
	['must_police'] = '¡Debe ser trabajador de la policía para acceder a esto!',
	['must_mechanic'] = '¡Debe ser mecánico para acceder a esto!',
	['you_paid'] = 'Has pagado ~g~€',
	['not_enough_money'] = '¡No tienes suficiente dinero!',
	['cant_in_veh'] = '¡Debe estar fuera del vehículo para acceder a esto!',
	['not_correct_veh'] = '¡No estás en el vehículo correcto para este garaje!',
	['driver_seat'] = '¡Debe estar en el asiento del conductor para almacenar el vehículo!',
	['visit_mechanic'] = 'Visite al mecánico o repárelo usted mismo.',
	['cannot_store_vehicle'] = '¡No puedes almacenar este vehículo!',
	['no_vehicle_to_enter'] = 'No hay ningún vehículo para almacenar en el garaje.',
	['vehicle_in_garage'] = 'Su vehículo está guardado en el garaje.',
	['veh_rename_empty'] = 'El nombre del vehículo debe tener entre %s & %s caracteres!',
	['veh_rename_no'] = 'El cambio de nombre del vehículo está desactivado actualmente.',
	['get_properties'] = '~y~¡Obteniendo garajes privados!',
	['large_trucks_no'] = '¡El concesionario de camiones no se utiliza en este servidor!',
	['spawnpoint_blocked'] = 'El punto de generación del vehículo está ~r~bloqueado~s~!',
}

**Comment by alartre** [comment]
Hi guys, i have same issue that @Nox7331 had. I am using master version in both resource (esx_advancedvehicleshop and esx_advancedgarage).

Have you made changes to anything in client/main.lua or server/main.lua?: nope
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: Yes, PLUME ESX
Are you using es_extended? If Yes what Version? (Example: 1.2.0): 
Are you using Essentialmode?: no
Are you using ExtendedMode?: no
Are you using OneSync?: no
Linux or Windows?: Linux


I will attach to you some images:

The issue that i recieve -->
![image](https://user-images.githubusercontent.com/47774813/116977105-52570680-acc2-11eb-98b8-7f37e3d41fb9.png)

MY owned_vehicle schema 
![image](https://user-images.githubusercontent.com/47774813/116977352-9ea24680-acc2-11eb-963f-34406ea0678a.png)

Im not using Steam ID --> 
![image](https://user-images.githubusercontent.com/47774813/116977419-b679ca80-acc2-11eb-9b0c-27d9b75bed40.png)


Do you know that am i doing wron @HumanTree92 ? Thanks for the inconvenience

**Comment by HumanTree92** [comment]
Category can't be null. It has to be a category like sports or supers.

**Comment by alartre** [comment]
Thank's a lot mate, thats resolve the problem. BTW maybe you should change this in your "esx_advancedvehicleshop.sql" because this can happend again if people follow the tutorial steps.


CREATE TABLE `owned_vehicles` (
	`owner` varchar(40) NOT NULL,
	`plate` varchar(12) NOT NULL,
	`vehicle` longtext,
	`type` VARCHAR(20) NOT NULL DEFAULT 'car',
	`job` VARCHAR(20) NOT NULL DEFAULT 'civ',
	`category` VARCHAR(50) DEFAULT NULL,
	`name` varchar(60) NOT NULL DEFAULT 'Unknown',
	`fuel` int(11) NOT NULL DEFAULT '100',
	`stored` TINYINT(1) NOT NULL DEFAULT '0',

	PRIMARY KEY (`plate`)
);


BTW Thank you so much ^^ Have a nice day @HumanTree92
