### ISSUE TITLE
When i press E it takes a lot of time to open garage

### ISSUE THREAD

**Issue by giannis97** [HumanTree92/esx_advancedgarage#228]
**Describe the Bug | A Clear & Concise Description of Bug**
as the title says, for every player when they press E to open any garage it takes a lot of time to show up the cars they owned

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  nope
Have you looked through the Closed Topics?:  nope
Have you looked through the Wiki?:  nope
Are you using a Pre-Installed ESX? If Yes who?: i am using esx 1.1
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.1
Are you using Essentialmode?: yes
Are you using ExtendedMode?: nope
Are you using OneSync?: yes
Linux or Windows?: Linux Ubuntu

**Comment by HumanTree92** [comment]
Are you using the Release or Master Version

**Comment by giannis97** [comment]
> Are you using the Release or Master Version

i am using this version version '1.0.0' what are the differences?

**Comment by HumanTree92** [comment]
Did you download the Release or the master version can you answer that. I don't update the Version

**Comment by lush0n3** [comment]
I downloaded the latest version and I am having this same problem.

**Comment by HumanTree92** [comment]
This is normal. If you check [here](https://github.com/HumanTree92/esx_advancedgarage/blob/master/client/main.lua#L1356) it waits to gather all of their owned vehicles. It has to run through each check which should only take a few seconds. If its taking longer its either b/c you are making too many MySQL checks or the player has lots of owned vehicles. On my server most players own about 40 Civ vehicles but the menu opens with all of their vehicles in about 1-2 secs.
