### ISSUE TITLE
Fuel SQL

### ISSUE THREAD

**Issue by Saitama5230** [HumanTree92/esx_advancedgarage#229]
**Latest update uses, legacy fuel for getting and inserting fuel to the vehicle, server side has a fuel sql table which is not included**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.1
Are you using Essentialmode?: yes
Are you using ExtendedMode?: no
Are you using OneSync?: yes
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
Must be blind b/c the SQL does have the fuel part. https://github.com/HumanTree92/esx_advancedgarage/blob/master/esx_vehicleshop_fix.sql#L11
