### ISSUE TITLE
How to create Vehicle_Names.Lua ?

### ISSUE THREAD

**Issue by LySoon** [HumanTree92/esx_advancedgarage#23]
![image](https://user-images.githubusercontent.com/49767982/56551012-e2b8c780-658f-11e9-91c3-ed6276293013.png)

![image](https://user-images.githubusercontent.com/49767982/56551016-e64c4e80-658f-11e9-984a-a43efc406e61.png)

i even added it to __resuorces.lua
but it wont work D: also why its not using vehiclenames from vehicles in database ?

Also.. thanks for any help & suggestion..

as i see this addon is so cool <3

**Comment by SerMighty** [comment]
Will be trying this myself today, i'll let you know how i do it if it works

**Comment by LySoon** [comment]
im waiting ^^

**Comment by HumanTree92** [comment]
I have the vehicle_names.lua where the addon car is at.

**Comment by LySoon** [comment]
Hmm, so i need to put .lua inside of every car mod ? Right??

**Comment by HumanTree92** [comment]
Not really. U only need 1 vehicle_names.lua if all your addon cars are in 1 file.

**Comment by LySoon** [comment]
İ seperated them to 4 folder each is 4gb ._. 
So want to ask you.. why we cant use vehicle names in vehicles.sql in mysql :?
Would be so nice
