### ISSUE TITLE
emergency and private vehicles in same garage?

### ISSUE THREAD

**Issue by weller197** [HumanTree92/esx_advancedgarage#230]
**Describe the Bug | A Clear & Concise Description of Bug**
Is there a way to get emergency and private vehicles to show in the garage at legion? or do i have to use the garages for the jobs?, i've had some complaints of emergency vehicles not showing in the garage at legion so the player had to go to their respected place of work to get a vehicle out.

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yse
Are you using a Pre-Installed ESX? If Yes who?: zap-hosting 
Are you using es_extended? If Yes what Version? (Example: 1.2): yes 1.2
Are you using Essentialmode?: yes
Are you using ExtendedMode?: no
Are you using OneSync?: yes
Linux or Windows?: windows

**Comment by HumanTree92** [comment]
You will have to do the job garages. As there is no easy way to have them all be in the same menu.
