### ISSUE TITLE
No name change function anymore!

### ISSUE THREAD

**Issue by DarkProvider** [HumanTree92/esx_advancedgarage#231]
**Describe the Bug | A Clear & Concise Description of Bug**

The old version of esx_advancedgarage had a "Change Name" and it used to use the other names it used to get from the esx_advancedvehicleshop, but now everything is back to NULL as for the custom vehicles. Are you planning on adding that function back any time soon?

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.2
Are you using Essentialmode?: yes
Are you using ExtendedMode?: no
Are you using OneSync?: yes
Linux or Windows?: Windows server

**Comment by HumanTree92** [comment]
The Master Version still has that. If your using the Release Version then it doesn't have that.

**Comment by DarkProvider** [comment]
Gotcha, cheers man
