### ISSUE TITLE
attempt to index a nil value (local 'vehicledata')

### ISSUE THREAD

**Issue by antbeezy** [HumanTree92/esx_advancedgarage#233]
**Describe the Bug | A Clear & Concise Description of Bug**
![image](https://user-images.githubusercontent.com/85043135/120088477-cff21480-c0be-11eb-901c-d404e53d385e.png)
When you leave the shop you can no longer use the blip to purchase/view vehicles that is the only problem that I am having

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: wiki links to website so unsure
Are you using a Pre-Installed ESX? If Yes who?: yes - zap
Are you using es_extended? If Yes what Version? (Example: 1.2):  Final 1.2
Are you using Essentialmode?: no
Are you using ExtendedMode?: no
Are you using OneSync?: yes
Linux or Windows?: windows

**Comment by HumanTree92** [comment]
Are you using Zaps pre-installed server files or did you install everything yourself?

**Comment by antbeezy** [comment]
> Are you using Zaps pre-installed server files or did you install everything yourself?

using the pre installed 1.2 final - it was removed for a while but they just fixed it as it was having issues

**Comment by antbeezy** [comment]
Awe man I meant to create a bug for your vehicleshop script not this one...

**Comment by HumanTree92** [comment]
Well either way my scripts require ESX V1 Final or EXM. They don't support ESX 1.2 or Zaps Pre-Installed ESX.

**Comment by antbeezy** [comment]
it is esx v1 final but in fxmanifest it shows as 1.2. I just downloaded esx v1 final straight from github and its the same exact errors in f8 - everything else works just not being able to use the marker after using it the first time

**Comment by antbeezy** [comment]
I dont know whats going on now but its working? .-.
