### ISSUE TITLE
When I try to get a car out of the garage, it says I don't have a car in the garage

### ISSUE THREAD

**Issue by MrSparkiop** [HumanTree92/esx_advancedgarage#234]
When I try to get my car out of the garage it says in the menu that I don't have a car in the garage and I don't know how to fix this problem you can see for yourself in the picture I tried everything I changed owned_vehicles with owned_vehicles_fix and it didn't happen I have no problems with Mysql no errors come out and I don't know how to solve this problem.
![Screenshot 2021-06-21 162356](https://user-images.githubusercontent.com/80846201/122770674-5bba2380-d2ae-11eb-9e87-03ece5227d8c.png)

**Comment by HumanTree92** [comment]
Post image of u owned_vehicles structure

**Comment by MrSparkiop** [comment]
![Screenshot 2021-06-21 202727](https://user-images.githubusercontent.com/80846201/122803404-3be72780-d2cf-11eb-9d5d-328f5d4dfc88.png)
![Screenshot 2021-06-21 202804](https://user-images.githubusercontent.com/80846201/122803408-3d185480-d2cf-11eb-8006-57b136974eeb.png)
Here are the photos you want.

**Comment by HumanTree92** [comment]
Are you using the Master or the Release version

**Comment by MrSparkiop** [comment]
> Are you using the Master or the Release version

I use the master version

**Comment by HumanTree92** [comment]
Then you need to be using my esx_advancedvehicleshop to purchase the vehicles

**Comment by MrSparkiop** [comment]
I also tried esx_advancedvehicleshop and nothing happened again I can't get my car out of the garage and the worst thing about the whole situation is that I don't have any error in the console and I don't know what to do about it I decided to write here because I have no idea I watched videos and read in the wiki I tried everything.

**Comment by HumanTree92** [comment]
Well there is no way you tried to use my esx_advancedvehicleshop. B/c if you did you wouldn't have this problem. Did u upload the SQL files for esx_advancedvehicleshop

**Comment by MrSparkiop** [comment]
I will try again but I really did all the steps and upload your file now I will try again and I will write after a while to say what the result is

**Comment by MrSparkiop** [comment]
> Well there is no way you tried to use my esx_advancedvehicleshop. B/c if you did you wouldn't have this problem. Did u upload the SQL files for esx_advancedvehicleshop

I tried the situation is the same and I can not find the problem if you want I can send you pictures of resources and the entire database and even when I use esx_advancedvehicleshop when I buy the car my character is invisible and when I get out of the car I can not move

**Comment by MrSparkiop** [comment]
I found the problem I had a theory which became the problem was that I use the master version and I have to use the realse version and left I can now take the cars out of the garage

**Comment by HumanTree92** [comment]
Judging from the Pictures you have sent this is what happened:
1. You where trying to use the Release Version. Which i no longer support.
2. If you where actually using the Master Version then the menu that pops up would be 100% different. It wouldn't even pop up if you didn't have any owned_vehicles and the master version doesn't have the locale for 'If Vehicle is NOT here Check Impound!!!'.
3. If you had the Master Version installed and had actually bought a vehicle from the esx_advancedvehicleshop then the owned_vehicles > category wouldn't be NULL and the name wouldn't be Unknown
