### ISSUE TITLE
 attempted to store an vehicle they don't own!

### ISSUE THREAD

**Issue by daniel13306** [HumanTree92/esx_advancedgarage#235]
**Describe the Bug | A Clear & Concise Description of Bug**
i buy a car, it shows up in owned (mysql) (but not in my garage)
and when i try to store it it says this: 

esx_advancedgarage: steam:11000010cb4022b attempted to store an vehicle they don't own!

No futher errors.

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No i havent
Have you looked through the Closed Topics?: i did, i searched the web for the string aswell
Have you looked through the Wiki?: i did
Are you using a Pre-Installed ESX? If Yes who?: installed it myself
Are you using es_extended? If Yes what Version? (Example: 1.2):  1.2
Are you using Essentialmode?: yes
Are you using ExtendedMode?: yes
Are you using OneSync?: yes
Linux or Windows?: linux (zap hosting)

**Comment by HumanTree92** [comment]
For one your not using the correct version from what the readme says to use. You need to upgrade to V1 Final. Also i'm not 100% sure if my garage system will work with steam identifiers.

**Comment by daniel13306** [comment]
i got it working with V2, awesome! only thing is sometimes the impound will tell: cant take out vehicle, and the car under it works, quite weird but ill take a look at it
