### ISSUE TITLE
renaming vehicles

### ISSUE THREAD

**Issue by Pesoen** [HumanTree92/esx_advancedgarage#237]
**Describe the Bug | A Clear & Concise Description of Bug**
Unable to rename vehicles, even tried looking through the code, but could not find out what was wrong. so far i have added the values to the config.lua, and tested the points both private and public garages, but no luck getting a "Rename/Spawn" menu to pop up. how exactly is the renaming supposed to work anyway? my understanding is i can have three neon's and change the name to drugmule1,drugmule2,drugmule3 and easier identify my vehicles. if that is not the case, i will just remove my rename changes to the config file.. no need for renaming if that's not the case.

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): legacy 1.3.5
Are you using Essentialmode?: Nope
Are you using ExtendedMode?: Nope
Are you using OneSync?: Nope
Linux or Windows?: Linux

**Comment by FreakOutModz** [comment]
This has nothing to do with the garage system

**Comment by HumanTree92** [comment]
So long as your using the latest version of this script if you set RenameVehs = false to true then you should be able to open the garage and select the vehicle category and then select rename and a dialog box should pop up allowing you to rename the vehicle.

**Comment by Pesoen** [comment]
was using the latest release(October 2020) gonna download the repo instead.
