### ISSUE TITLE
Unable to retrieve stored vehicles│All vehicles that are stored are added to the database│Using Advanced Vehicle Shop to Purchase Vehicles

### ISSUE THREAD

**Issue by RossDanbyGamer** [HumanTree92/esx_advancedgarage#238]
**Describe the Bug | A Clear & Concise Description of Bug**

Hi, I'm been trying to add this garage script into my FiveM Server. I've tried following a YouTube guide for settings this up as well as reading the Wiki and Closed Issues. I've been trying things for hours but have always had the same issue. No errors are being logged in the console. You can store the vehicle which adds it to the database but when you try to retrieve it I don't see any vehicles which are in the database appearing in the menu. I've download from master and not releases to get the up to date code. Please can you help me get this up and running, sorry in advanced if this is a common scenario but haven't been able to work this out myself so far. Below are some screenshots, one of the notification after I buy a vehicle confirming that it belongs to me. The other showing the empty menu where no vehicles are displayed as well as another screenshot of the database and the columns inside the table. Hopefully that gives you enough information to understand my issue and hopefully get it solved easily so that others can refer to this issue for help. 
![Owned_Vehicles Database Columns](https://user-images.githubusercontent.com/28724027/128211708-42619dbf-6b38-404b-85b0-a18681a1e485.png)
![Owned_Vehicles Database](https://user-images.githubusercontent.com/28724027/128211723-3058c8ee-c71f-4276-abc3-ac60c0d1e824.png)
![Confirmation Of Vehicle Ownership](https://user-images.githubusercontent.com/28724027/128211741-e64c60c7-9207-4bc6-8cd3-6f2156eafcf5.png)
![Garage Menu](https://user-images.githubusercontent.com/28724027/128211753-5d905214-f992-480a-91f2-d5b752280704.png)

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.3.8
Are you using Essentialmode?: Yes
Are you using ExtendedMode?: No
Are you using OneSync?: Yes
Linux or Windows?: Linux

**Comment by astron51** [comment]
Make sure the vehicle Category are loaded from SQL.

**Comment by RossDanbyGamer** [comment]
Thanks for pointing this out. I understand now. The category "super" should have been "supers" after looking around. Appreciate you commenting and I can finally close this issue 🙂
