### ISSUE TITLE
Error starting script

### ISSUE THREAD

**Issue by Brutuss** [HumanTree92/esx_advancedgarage#240]
**Describe the Bug | A Clear & Concise Description of Bug**
I have downloaded and installed the Resource. Disabled the default esx_garage. Imported the SQL
Started the esx_advancedgarage and the following error is shown:

[    c-scripting-core] Creating script environments for esx_advancedgarage
[    c-scripting-core] Failed to load script @es_extended/imports.lua.
[script:esx_advancedg] Error loading script server/main.lua in resource esx_advancedgarage: @esx_advancedgarage/server/main.lua:31: attempt to index a nil value (global 'ESX')
[script:esx_advancedg] stack traceback:
[script:esx_advancedg] 	@esx_advancedgarage/server/main.lua:31: in main chunk
[    c-scripting-core] Failed to load script server/main.lua.
[ citizen-server-impl] Started resource esx_advancedgarage
[script:esx_advancedg] esx_advancedgarage: Parking Vehicles on restart is currently set to false.

I have found a possible sollution on your website under: 
"Getting this to work with esx_property" 
Because i think it has to do with that. 
But i can't find the lines mentioned. 

"TriggerClientEvent('esx_property:setPropertyOwned', xPlayer.source, name, true, rented)"
I found: 
TriggerClientEvent('esx_property:setPropertyOwned', xPlayer.source, name, true)

Second line didn't find at al:
"xPlayer.triggerEvent('esx_property:setPropertyOwned', name, false)"

**Questions**
Have you made changes to anything besides the `config.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using ESX Legacy?: Yes
Are you using OneSync?: Yes
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
My latest version only supports ESX Legacy.

**Comment by Brutuss** [comment]
Thank you for your answer. Is there something I can do? Because I have started with esx legacy. 

Maybe I need to use an older version then?

**Comment by Brutuss** [comment]
I have solved it using the "Old release" then added the database so the job line wil default at 'civ'.

**Comment by HumanTree92** [comment]
As i have seen a few people with this problem. A few things to make sure is that you are 100% using ESX Legacy. Make sure that the main file for ESX is called es_extended and that there is an imports.lua file inside.

**Comment by Brutuss** [comment]
Don't have a imports.lua :( so i don't have the correct ESX. Is it possible te replace? Better to do so or not?
