### ISSUE TITLE
category add?

### ISSUE THREAD

**Issue by timonation** [HumanTree92/esx_advancedgarage#241]
how can i add categorys. i have tuning category at the shop but i cant get it out because the category is not shown in menu

**Questions**
Have you made changes to anything besides the `config.lua`?: yes
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: 
Are you using ESX Legacy?: no v1 final
Are you using OneSync?: yes
Linux or Windows?:  windows

**Comment by HumanTree92** [comment]
You will just have to look on how its done with the default vehicles. And just copy and paste it over. Its hard to explain.
