### ISSUE TITLE
Cars Cannot be found after parking

### ISSUE THREAD

**Issue by Erani0** [HumanTree92/esx_advancedgarage#244]
**Describe the Bug | A Clear & Concise Description of Bug**
After restarting the server, the cars can be found in the category after the car has been taken out of the rack and parked again, the category can no longer be found and the car can therefore no longer be found

**Questions**
Have you made changes to anything besides the `config.lua`?: yes
Have you looked through the Closed Topics?: 
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using ESX Legacy?: Yes
Are you using OneSync?: Yes
Linux or Windows?: Linux

**Comment by HumanTree92** [comment]
Did you happen to find this issue. The only other thing i would try doing is increasing the wait time. Located here https://github.com/HumanTree92/esx_advancedgarage/blob/master/client/main.lua#L1340

**Comment by HumanTree92** [comment]
Closing issue as i can see its not an issue with this script. You need to fully make sure that whatever you changed is working. However i don't support people who edit anything outside of the config.lua unless you know what your doing.
