### ISSUE TITLE
I can not park and unpark cars

### ISSUE THREAD

**Issue by FritLP** [HumanTree92/esx_advancedgarage#245]
**Describe the Bug | A Clear & Concise Description of Bug**

First of all, I have followed all the steps of the instructions exactly and checked several times. But now when I buy a car from the store and try to park it, I get the message "you can not park this vehicle" (on the picture in German) and when I go to park out comes "Translation [en][garage_no_veh] does not exist".

Can you help me further?

**Questions**
Have you made changes to anything besides the `config.lua`?:  Yes, i activated the garages
Have you looked through the Closed Topics?:  Yes
Have you looked through the Wiki?:  Yes
Are you using a Pre-Installed ESX? If Yes who? : Plume ESX 3.3.0 
Are you using ESX Legacy?:  Yes
Are you using OneSync?: No
Linux or Windows?: Windows

**Comment by mrvn7rp** [comment]
Save Issue and get this error:

**Comment by mrvn7rp** [comment]
[script:esx_advancedg] SCRIPT ERROR: @esx_advancedgarage/server/main.lua:246: bad argument #1 to 'pairs' (table expected, got nil)

**Comment by HumanTree92** [comment]
Few Questions:
1. What do you have set for Config.Locale?
2. esx_advancedgarage/server/main.lua:246 points to https://github.com/HumanTree92/esx_advancedgarage/blob/master/server/main.lua#L246 which is cycles. So which vehicleshop are you using?
3. Are you using the Release or Master Version of this script?
4. You say you changed something else outside of the config.lua which file did you change?

**Comment by FritLP** [comment]
1.
Config = {}
Config.Locale = 'en'

2. I am using your esx_advancedvehicleshop

3. The Master Version (by advancedvehicleshop the master too)

4. Oh sorry, I misread. I have not changed anything except the config. 


Here you can see my MySQL owned_vehicles:

[](https://i.ibb.co/ncCVthS/owned-vehicles.png)

It is all the same owner, however before the 2nd vehicle was created I think I deleted esx_multicharacter, however this did nothing

**Comment by FritLP** [comment]
*I found this in my Live Log, when i start my Server right now

https://i.ibb.co/BCfmYzP/console-log.png

**Comment by FritLP** [comment]
Oh i fixed it.. the Problem was that i deletet the normal esx_vehicleshop and now i disabled it only.. but how can i give addon cars in the users garage?

**Comment by HumanTree92** [comment]
If you wanted to give a person a car you can edit the DB. It kinda hard. You can add cars to a addon garage via the db as well.
