### ISSUE TITLE
Car Garage don't work (is this script outdated/broken?)

### ISSUE THREAD

**Issue by mrvn7rp** [HumanTree92/esx_advancedgarage#246]
**Describe the Bug | A Clear & Concise Description of Bug**
I installed everything correctly, with SQL and so on.
You can park the car, but if you want to get it from the garage is says you don't own any vehicles for this garage.
Also it gives an error, but the car is created in the owned_vehicles table.
Is this script still up to date or just broken and no support?

**Questions**
Have you made changes to anything besides the `config.lua`?: nö
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: yes, Plume-ESX-Legacy
Are you using ESX Legacy?: yes
Are you using OneSync?: no
Linux or Windows?: Windows V Server

**Comment by HumanTree92** [comment]
Yup. Nothing wrong with the script. Works perfectly fine. Show an image of your owned_vehicles structure. Also are you using the Release or the master version?

**Comment by mrvn7rp** [comment]
Oh yeah it was just an SQL problem, sorry for that!
When you use the old garage before and try to execute the sql file it just end and dont add category and so on.
But I found a little bug, it don't showed the super cars category in the garage, its because in the server main.lua in line 370 it says ['@category'] = 'supers' but it should be ['@category'] = 'super' 
Thanks for the great work!

**Comment by HumanTree92** [comment]
Nope your wrong. If your using my esx_advancedvehicleshop the category supers is correct.

You can see here:
https://github.com/HumanTree92/esx_advancedvehicleshop/blob/master/esx_advancedvehicleshop.sql#L292
https://github.com/HumanTree92/esx_advancedvehicleshop/blob/master/esx_advancedvehicleshop.sql#L563
https://github.com/HumanTree92/esx_advancedgarage/blob/master/server/main.lua#L364
