### ISSUE TITLE
Remove Category

### ISSUE THREAD

**Issue by Arcticguy867** [HumanTree92/esx_advancedgarage#247]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything besides the `config.lua`?: no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: yes
Are you using ESX Legacy?: no
Are you using OneSync?: yes
Linux or Windows?: Windows

Is there a way to remove the category like super and off-road etc 
but still have the rename feature

**Comment by HumanTree92** [comment]
You could yes. However after a certain amount of vehicles the menu will break. Most of the time if there is like 36 vehicles listed in a single menu the menu will break for that person. Then they would have to relog to fix the issue. But when they opened the menu it would break again. Doing it this way makes it easier.

**Comment by Arcticguy867** [comment]
but in some servers i have people have it and they have more than 80 cars

**Comment by HumanTree92** [comment]
It all depends on what Menu they are using. It also depends on what garage script they are using. There are too many out there. And if they are using mine they could either be using the Release or the Masters version. But as for changing the master to list all the cars you would have to make a lot of changes to the script.
