### ISSUE TITLE
Not a bug, but a question

### ISSUE THREAD

**Issue by FritLP** [HumanTree92/esx_advancedgarage#248]
I hope it's ok that I ask you here. Is it possible to personalize the design of the parking? (see screenshot)

Screenshot:

https://i.ibb.co/CMSwCtb/Garage-ausparken-screen.png

Best wishes

**Comment by HumanTree92** [comment]
To change its colors look here https://github.com/esx-framework/esx-legacy/tree/main/%5Besx%5D/esx_menu_list
