### ISSUE TITLE
Question to the ParkVehicles flag

### ISSUE THREAD

**Issue by miwi-fbsd** [HumanTree92/esx_advancedgarage#250]
**Describe the Bug | A Clear & Concise Description of Bug**

Hey,

Is there a chance to make this "ParkVehicles = false" flag complete off currently it conflicts with another script:
https://forum.cfx.re/t/release-advancedparking-prevents-despawns/2099582 ,

Much apricated you support.

**Questions**
Have you made changes to anything besides the `config.lua`?:  no
Have you looked through the Closed Topics?:  yep
Have you looked through the Wiki?:  yep
Are you using a Pre-Installed ESX? If Yes who?: no 
Are you using ESX Legacy?:  yes
Are you using OneSync?:  no
Linux or Windows?:  linux

**Comment by HumanTree92** [comment]
I don't see how a Config setting conflicts with another script. By setting ParkVehicles to true it means on server start or restart it will change the stored value to true. But setting it to false doesn't change anything.
