### ISSUE TITLE
Storing Society Vehicles?

### ISSUE THREAD

**Issue by SerMighty** [HumanTree92/esx_advancedgarage#28]
Noticed that you cannot park Society Bought/Owned Vehicles at the regular garages? Says "You cannot park this" of course as they are marked as owned by society:jobname in the DB.

Been testing it with the Mechnanics and if we use the Vehicle Deleter/Store they despawn but do not get marked as stored in the DB (I know that is to do with esx_mechanicjob but just an example) 

Is there something i'm missing with regards to society owned vehicles or is it not supported?

If it isn't i'll look to get it in and do a PR :)

Thanks

**Comment by HumanTree92** [comment]
Yeah not supported but if u want to make a pr u can. If I like it I will accept it. You will also need to make sure that the society owned vehicles is separate from everything else. Example I don't want police cars getting pulled from car garage bc this means if someone isn't cop they can still pull out the vehicle. So u would need to figure out a way to do that. I can do it when I get the chance to.

**Comment by HumanTree92** [comment]
Also there is a limit to how many vehicles can show up on the list. For me it's 36 before it breaks. But all in all if u do decide to take a crack on it u will need to do every job that has society vehicles. And the location needs to be the default job location

**Comment by HumanTree92** [comment]
I can do this in the next week once i get done with what i am doing now.

**Comment by SerMighty** [comment]
No problem, i'll be taking a look at it and seeing how it can be integrated, if i come up with something i'll let you know, appreciate you taking the time to check it out when you're finished with your current work.
