### ISSUE TITLE
[Error] ShowHelpNotification

### ISSUE THREAD

**Issue by DrPeluche** [HumanTree92/esx_advancedgarage#3]
While going in a circle, console displays this error:

"Error resuming coroutine: client/main.lua:783: attempt to call a nil value ( field 'ShowHelpNotification')
stack trackback: client/main:783: in function client/main.lua:778"

I do not understand why he can not retrieve CurrentActionMsg in ESX.ShowHelpNotification(CurrentActionMsg)

**Comment by HumanTree92** [comment]
This really isn't an issue. As it works fine for me & others. Not sure why this is happening. Is it happening to you or another player.

**Comment by DrPeluche** [comment]
all players on the server unfortunatly. As a bypass, i commented the line and everything works fine

**Comment by HumanTree92** [comment]
What you can do is comment out line 783 & add 
```lua
                        SetTextComponentFormat('STRING')
			AddTextComponentString(CurrentActionMsg)
			DisplayHelpTextFromStringLabel(0, 0, 1, -1)
```
