### ISSUE TITLE
cant spwan cars out of garage

### ISSUE THREAD

**Issue by FreeLiveRP** [HumanTree92/esx_advancedgarage#31]
Hello, i dont can spwan cars out of garage all time when i press e my game has a freez can you help me

**Comment by HumanTree92** [comment]
Without any errors not sure what to go on. Please explain more.

**Comment by jamesfill** [comment]
I will explain more clearly to you about this issue.

1. When i owned vehicle then i go to the public garage to store it -> It's work well.

2. When i come to the green area to take out the car it have notify "You are not own any vehicle" and the menu not display a list of owned car. I happened with Impound Garage, Boat, Aircraft too. 

Here is the error code

![2019-05-08_110730](https://user-images.githubusercontent.com/26543244/57350318-d6d02680-7187-11e9-90f8-35b8aa249606.png)

![2019-05-08_110740](https://user-images.githubusercontent.com/26543244/57350334-ed767d80-7187-11e9-8e7e-469ef428417c.png)

![2019-05-08_110830](https://user-images.githubusercontent.com/26543244/57350383-1991fe80-7188-11e9-9143-12fc46c9eb32.png)

**Comment by genosh** [comment]
I have the same problem with the same error.
I suppose that vehicle is well stored on garage because on database vehicle is mantionned by "stored = 1).
But it found no vehicles when I try to get the vehicle...

**Comment by HumanTree92** [comment]
https://github.com/HumanTree92/esx_advancedgarage/wiki/Home---Bugs,-Questions,-Etc-that-have-been-fully-answered
