### ISSUE TITLE
Can't disable paying for damaged car

### ISSUE THREAD

**Issue by j127t** [HumanTree92/esx_advancedgarage#32]
I believe I have disabled paying to store a damaged car, but it still charges when I do.  Maybe I am missing a piece of code I need to alter somewhere.  Also, when it does charge for storing a damaged vehicle, if I don't have cash on hand, it puts my cash into negative so when I withdraw say $100 the next time I go to an ATM it withdraws $100-my parking debt.  Any way to make this pull from a bank account instead?  Preferably I just want to disable the cost to store a damaged vehicle and/or storing the vehicle in its current state instead of fixing it on storage.

**Comment by HumanTree92** [comment]
I have no plans to remove or allow people to remove not paying for damage vehicles. As for setting it to cash in Bank instead i am pretty sure you can set this up yourself. It would be nice if ESX had say a Credit/Debit Card Script instead. Where if you had a Credit/Debit Card you could use that instead.
