### ISSUE TITLE
[Quesiton] Ordering

### ISSUE THREAD

**Issue by WoodyBRUH** [HumanTree92/esx_advancedgarage#33]
Was just wondering if there is a way to reorganise the order of stored vehicles when a player opens their garage or could you add something to the config that lets people decide whether they want cars order by licence plate or vehicle name?

**Comment by HumanTree92** [comment]
Currently there isn't a way. It only supports by plate name. Plus i don't have the time anymore to try and find a fix. But if you find one let me know & i will try to implement it.

**Comment by WoodyBRUH** [comment]
Sure thing, i'll drop the updated code here once i figure it out, thanks anyway
