### ISSUE TITLE
Cars are displayed as "NULL"

### ISSUE THREAD

**Issue by BoutProduction** [HumanTree92/esx_advancedgarage#4]
Hello HumanTree92,
First of all, I would like to thank you for publishing this garage script.

But I have a problem!
The addon vehicles are displayed as "NULL", and I do not know how to fix something ... I hope that you have a solution to this problem

Greetz
BoutProduction

- Screenshot:
http://prntscr.com/mi1n1q

**Comment by HumanTree92** [comment]
You are missing the vehicles_names.lua file. This is needed.

**Comment by HumanTree92** [comment]
Fixed in eeee38585f4546b8f45e2208c6e302eed67cdfa0
