### ISSUE TITLE
Can't sell vehicles after spawning out of garage?

### ISSUE THREAD

**Issue by kysimuden** [HumanTree92/esx_advancedgarage#42]
Hello,
I'm using the newest ESX_vehicleshop version.
The case is when i buy a car form the car dealer I can resell it immediately, but i couldnt do it when i store it in the garage then spawn it again. (It says i'm not the owner of the car at the car dealer resell, but i can still store that car in the garage)
The console shows a steam id is attempting to sell a mismatch vehicle plate
I've tried to buy a car and leave it outside, then restart the server so it can be stored automatically. The interesting thing is that I can resell that car after spawning it at the garage!?
Can you tell me what is the cause of this problem and show me how to solve it?
Thank you very much!

**Comment by HumanTree92** [comment]
Last time i had this happen i did the command to reset plates.

**Comment by 31549662** [comment]
how can I reset plates?
