### ISSUE TITLE
Add-on vehicle name is NULL

### ISSUE THREAD

**Issue by Robijntjee** [HumanTree92/esx_advancedgarage#49]
Hey guys,
I have a small problem with esx_advancedgarage
I have added add-on vehicles to my FiveM Server, only there is now NULL instead of Audi RS3 Audi RS6 Audi RS7 et cetera, how do I change this?

![image](https://user-images.githubusercontent.com/51093268/58433146-0b177280-80b6-11e9-8021-85ea05528e9c.png)

regards,

**Comment by HumanTree92** [comment]
[Check the Wiki](https://github.com/HumanTree92/esx_advancedgarage/wiki)
