### ISSUE TITLE
Cant store cars in Onesync

### ISSUE THREAD

**Issue by SliderKP** [HumanTree92/esx_advancedgarage#55]
No way to solve this bug?

**Comment by tantanpro1612** [comment]
When not in the main driver's seat, I can store the car without making my car it disappear, and then I can take more cars for free.
@HumanTree92

**Comment by HumanTree92** [comment]
Don't have OneSync so i don't know.

**Comment by SliderKP** [comment]
u are no planning to update to OneSync?, i want to solve this bug :( @HumanTree92
I've been trying to fix it for a long time and I can not find a solution

**Comment by HumanTree92** [comment]
I plan on in the future. But since my server went from popular to nobody on it i have no plans yet.

**Comment by SliderKP** [comment]
my server is also going to have less people, but when I implement 64 slots, I get more than 40 users daily, I think the public looks for wide servers too ... 32 slots is already very boring ...

okey i will wait your update to fix this error, good luck with your server, and thanks for your answer.

**Comment by danishrp** [comment]
My take on this, it's all about net id :) it's actually ESX that needs to update there routin on deleting vehicles.

Example. https://forum.fivem.net/t/can-someone-please-make-a-dv-or-delgun-or-vehicle-cleanup-sricpt-that-works-with-onesync/523877/13

**Comment by SliderKP** [comment]
this was fixed.

**Comment by dwiprizzy** [comment]
how to fix it ?

**Comment by SliderKP** [comment]
> how to fix it ?

just update your fivem version
