### ISSUE TITLE
Attempt to index a nil global value "Config" 

### ISSUE THREAD

**Issue by MrMallenby** [HumanTree92/esx_advancedgarage#65]
![20190718172128_1](https://user-images.githubusercontent.com/4685327/61474492-b0491b80-a980-11e9-850d-b9b955f1ea8b.jpg)
So i have just installed the script fresh and im running into this issue, i tried capitalising the "c" in the name of the config file and no luck

**Comment by HumanTree92** [comment]
Could be a script load order problem. Not sure. Nobody else has this issue
