### ISSUE TITLE
No popup for repair

### ISSUE THREAD

**Issue by TheRealDadbeard** [HumanTree92/esx_advancedgarage#67]
So storing a damaged car doesn't ask me if I want oto repair it. I laready enabled it in the config.

But would it be possible to save the car as damaged as it is so that people are forced to go to the mechanic?

**Comment by HumanTree92** [comment]
If its not asking you to repair a damaged car then you installed it wrong b/c its working just fine for me. Also on the second question no its not possible.

**Comment by TheRealDadbeard** [comment]
Idk know what could went wrong while copying the files and then adding it to the servercfg.

I think it should repair even if you have the smallest scratch? Going to reinstall to see if it fixes anything

**Comment by HumanTree92** [comment]
Do you have OneSync?

**Comment by TheRealDadbeard** [comment]
Okay so I now really damaged the car and it popped up. Other than that I ditched the boat script that I had and switched to yours. Don't know if that was the issue but now it worked.

Would it be possible to get the vehicle health and save it into mysql? I started to dabble in lua and maybe if I'm good enough I could add something like this if even possible
