### ISSUE TITLE
You can not store this vehicle

### ISSUE THREAD

**Issue by minifondue** [HumanTree92/esx_advancedgarage#69]
![image](https://user-images.githubusercontent.com/52504608/62055847-947a2b00-b246-11e9-9334-62dd33ba04e2.png)
And in cmd is show like that 
esx_advancedgarage: steam:11000010f9591d8 attempted to store an vehicle they don’t own!

I have this error (in attach picture above) then I try to use vehicleshop.sql and your sql it's same error. How can I fix that? I can't store any vehicles

in DB it save that data but vehicle is still appear (usually if store vehicle it will disappear)

**Comment by HumanTree92** [comment]
That error is telling you that there is a problem in your DB.
