### ISSUE TITLE
stored default values

### ISSUE THREAD

**Issue by plutonmania** [HumanTree92/esx_advancedgarage#7]
#2 hello, i had before other script garage the latest was jb eden garage. I wanted to test your script but this error appears:
```
> `[
[ERROR] [MySQL] [esx_advancedgarage] An error happens on MySQL for query "[object Object]": ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'stored = true WHERE stored = false' at line 1
`


Error: (node:12324) UnhandledPromiseRejectionWarning: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'stored = true WHERE stored = false' at line 1
    at Query.Sequence._packetToError (mysql-async.js:244:14)
    at Query.ErrorPacket (mysql-async.js:2109:18)
    at Protocol._parsePacket (mysql-async.js:5941:23)
    at Parser.write (mysql-async.js:6198:12)
    at Protocol.write (mysql-async.js:5701:16)
    at Socket.<anonymous> (mysql-async.js:693:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Pool.query (mysql-async.js:4728:23)
    at Promise (mysql-async.js:4970:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:4967:26)
    at Object.global.exports [as callback] (mysql-async.js:4985:5)
    at citizen:/scripting/v8/main.js:87:41
    at window.TriggerEventInternal (citizen:/scripting/v8/natives_server.js:498:9)
    at global.emit.args (citizen:/scripting/v8/main.js:141:3)
    at global.on (mysql-async.js:5075:16)
    at citizen:/scripting/v8/main.js:193:28
Error: (node:12324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Error: (node:12324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.



```
```

> Uncaught AssertionError [ERR_ASSERTION]: unexpected PromiseRejectEvent
> internal/errors.js(102,11): AssertionError
> assert.js(42,9): innerFail
> assert.js(56,3): fail
> internal/process/promises.js(27,25):
> mysql-async.js(4973,13): db.query
> mysql-async.js(280,24): Sequence.end
> mysql-async.js(2122,8): Query.ErrorPacket
> mysql-async.js(5941,23): Protocol._parsePacket
> mysql-async.js(6198,12): write
> mysql-async.js(5701,16): Protocol.write

```

[table owner_vehicles](https://i.imgur.com/0euK5tb.jpg)

I have installed the latest version esx_vehicle shop, delete the table owner_vehicle and delivered that

> CREATE TABLE `owned_vehicles` (
> `owner` varchar (22) NOT NULL,
> `plate` varchar (12) NOT NULL,
> `vehicle` longtext,
> `type` VARCHAR (20) NOT NULL DEFAULT 'car',
> `job` VARCHAR (20) NOT NULL,
> `stored` TINYINT (1) NOT NULL DEFAULT '0',
> 
> `` `
> PRIMARY KEY (`plate`)
> `` `
> 
> );

**Comment by HumanTree92** [comment]
Not really an issue with this script. As i have a lot of other people using this without an error.

**Comment by HumanTree92** [comment]
Since i got that from esx_boat. Here is where they are talking about how to fix that. https://github.com/ESX-Org/esx_boat/issues/9

Other than that i have no clue on how to fix it. Seems to me like its more of a problem with your mysql. I will keep this issue up until i find a fix for it.

**Comment by HumanTree92** [comment]
Quick question are you using the latest mysql?
If so make sure your mysql_connection_string is correct. If your hosting the FiveM server yourself & not through a hosting company like Zap make sure the server=localhost

**Comment by plutonmania** [comment]
hello . yes i use the latest mysql , i have the 6.2 essentielmode.
and my mysql is : ################################################################################
set mysql_connection_string "server=localhost;uid=########;password=########;database=essentialmode"
################################################################################

**Comment by HumanTree92** [comment]
What you could try is in the server/main.lua for esx_advancedgarage comment out lines 6-18 & try 
```lua
AddEventHandler('onMySQLReady', function()
	MySQL.Sync.execute("UPDATE owned_vehicles SET stored=true WHERE stored=false", {})
end)
```

**Comment by mrfuge** [comment]
Hello, i too am having the same problem. I tried the post you linked, from the boats script, and I already had those lines. I also tried what you just pasted above, which also did not work.

**Comment by mrfuge** [comment]
Could it possibly be here? seems like it's repeated.

-- Make sure all Vehicles are Stored on restart
MySQL.ready(function()
	ParkVehicles()
end)

function ParkVehicles()
	MySQL.Async.execute('UPDATE owned_vehicles SET stored = true WHERE stored = @stored', {
		['@stored']      = false
	}, function (rowsChanged)
		if rowsChanged > 0 then
			print(('esx_advancedgarage: %s vehicle(s) have been stored!'):format(rowsChanged))
		end
	end)
end

**Comment by HumanTree92** [comment]
@mrfuge  It is that i think. However tho not sure why. B/c it works for me & a bunch of others. And its only called once. Unless you restart the script.

**Comment by Garik0w** [comment]
I solved its with: 
`	MySQL.Async.execute('UPDATE owned_vehicles SET stored=true WHERE stored=@stored', {['@stored']= false}`

**Comment by mrfuge** [comment]
> I solved its with:
> 
> > function ParkVehicles()
> > MySQL.Async.execute('UPDATE owned_vehicles SET stored = true WHERE stored = @stored', {['@stored']= false}
> > function (rowsChanged)
> > if rowsChanged > 0 then
> > print(('esx_advancedgarage: %s vehicle(s) have been stored!'):format(rowsChanged))
> > end
> > end)
> > end

Hmm. I tried this and got the following when starting the server:

Error parsing script server/main.lua in resource esx_advancedgarage: server/main.lua:13: ')' expected (to close '(' at line 11) near 'function'
Failed to load script server/main.lua.

**Comment by Garik0w** [comment]
I have tried with several versions of mysql_async, both version 2 and version 3, all updated to the last, and that same error keeps appearing, I do not really know why they work for others, but ami certainly not. Previously I used MariaDB, but move to SQL Server 8 and we continue the same. Did you find any solution? a greeting!

**Comment by Garik0w** [comment]
Well after several attempts to solve this problem, I did it, I must thank benzon, since I have used part of their help as is the case of the BD of owned_vehicles, all those people who skip said message, there is what to do the following:

1- Use the database with the data:
```
CREATE TABLE `owned_vehicles` (
`owner` varchar (22) NOT NULL,
`plate` varchar (12) NOT NULL,
`vehicle` longtext,
`type` VARCHAR (20) NOT NULL DEFAULT 'car',
`job` VARCHAR (20) NOT NULL DEFAULT '',
`stored` TINYINT (1) NOT NULL DEFAULT '0',

PRIMARY KEY (`plate`)
);
```

2- Realize this as an example in all the code:

ORIGINAL:
`MySQL.Async.execute('UPDATE owned_vehicles SET stored = true WHERE stored = @stored', {`
MODIFIED:
`MySQL.Async.execute('UPDATE owned_vehicles SET `stored` = true WHERE `stored` = @stored', {`


I hope it works for you, if so, I hope that HumanTree92 manages to guess why it is failing for some, I am not very expert for it, even so thank you very much for this great code.

**Comment by Garik0w** [comment]
Now you get as many cars as you want, I guess it's got to see something in relation to the stored code ... I have to look at it carefully

**Comment by mehonja** [comment]
I had the issue that the actual data in the table was tinyint(1) and the query was using "true" and "false". MySQL couldn't handle it.

Now, i'm not a MySQL expert, but far as i know MySQL doesn't support boolean types in tinyints's.

Change the query, to use 1 and 0, instead of true and false, respectively, and it should work.

Cheers.

**Comment by Garik0w** [comment]
The only problem with this process is that when the vehicle is in the deposit you can take it out as many times as you want, that if paying the fee, I think there is a problem with the DontShowPoundCars or something similar, but I can not make it work ...

**Comment by HumanTree92** [comment]
Hopefully fixed this issue with the latest update. If not please reopen this issue.

**Comment by edellenburg** [comment]
Hey guys a run across your post on goggle. I'm have similar issue and came here for help. I have a windows server with all the same file in database and it runs fine. I installed on linux and ftp my resource folder and have been getting nothing but errors and headaches. I have tried with mysql 2.0 and 3.0. but get errors. Any help would be much appreciated.

[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM truck_categories {=}": Unable to connect to any of the specified MySQL hosts.
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM trucks {=}": Unable to connect to any of the specified MySQL hosts.
Error running system event handling function for resource esx_truckshop: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @esx_truckshop/server/main.lua:27: attempt to get length of a nil value (local 'vehicles')
stack traceback:
        @esx_truckshop/server/main.lua:27: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM shops LEFT JOIN items ON items.name = shops.item {=}": Connect Timeout expired.
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM datastore {=}": Unable to connect to any of the specified MySQL hosts.
Error running system event handling function for resource esx_datastore: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @esx_datastore/server/main.lua:14: attempt to get length of a nil value (local 'result')
stack traceback:
        @esx_datastore/server/main.lua:14: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM items {=}": Unable to connect to any of the specified MySQL hosts.
Error running system event handling function for resource esx_addoninventory: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @esx_addoninventory/server/main.lua:14: attempt to get length of a nil value (local 'items')
stack traceback:
        @esx_addoninventory/server/main.lua:14: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM addon_account {=}": Unable to connect to any of the specified MySQL hosts.
Error running system event handling function for resource esx_addonaccount: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @esx_addonaccount/server/main.lua:12: attempt to get length of a nil value (local 'result')
stack traceback:
        @esx_addonaccount/server/main.lua:12: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
[ERROR] [MySQL] An error happens on MySQL for query "UPDATE owned_vehicles SET state=true WHERE state=false {=}": Unable to connect to any of the specified MySQL hosts.
[ERROR] [MySQL] An error happens on MySQL for query "UPDATE owned_vehicles SET `stored` = true WHERE `stored` = false AND type = @type {@type=boat}": Connect Timeout expired.
Sending heartbeat to live-internal.fivem.net:30110
No such command stack.
hitch warning: frame time of 203055 milliseconds
cfx>         @esx_society/server/main.lua:31: in upvalue 'handler'
No such command @esx_society/server/main.lua:31:.
cfx>         citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:[ERROR] [MySQL] An error happens on MySQL for query "SELECT * FROM properties {=}": Connect Timeout expired.
No such command citizen:/scripting/lua/scheduler.lua:219:.
cfx> [ERROR] [MySQL] An error happens on MySQL for query "UPDATE owned_vehicles SET stored = true WHERE stored = @stored {@stored=False}": Connect Timeout expired.
No such command [ERROR].

**Comment by HumanTree92** [comment]
@edellenburg The problem ur having is u can't find the mysql host. That is not this scripts fault
