### ISSUE TITLE
Engine mods

### ISSUE THREAD

**Issue by TehAkisGR** [HumanTree92/esx_advancedgarage#75]
Hello, i have a problem, my engine mods are saving on the database and work when im leaving the mechanic shop but when i put the car in the garage and get it out it has the mod but it goes like stock.

**Comment by HumanTree92** [comment]
Are you using OneSync?

**Comment by TehAkisGR** [comment]
No im not using onesync nor any other scripts that mess with engine mods or garages

**Comment by HumanTree92** [comment]
Ok um is there any errors in the logs?

**Comment by TehAkisGR** [comment]
nope anything, not even a warning on mysql it runs smooth

**Comment by HumanTree92** [comment]
That's weird then. There really isn't anything to go off on then.

**Comment by TehAkisGR** [comment]
I'm starting to believe that this is a problem with es_extended and i waste ur time here, i really dont know tho.....

**Comment by HumanTree92** [comment]
Is it a Windows or Linux server.

**Comment by TehAkisGR** [comment]
It's a windows vps server

**Comment by HumanTree92** [comment]
If your still having this problem check out my [wiki](https://github.com/HumanTree92/esx_advancedgarage/wiki) I'm pretty sure the Vehicles coming out Broken/Damaged might be the problem.

**Comment by TehAkisGR** [comment]
I have the es_extended/client/functions,lua engine health and bodyhealth but still the same issue,

**Comment by HumanTree92** [comment]
Also can u be a little bit more in detail what u have tried. Can u send me ur server.cfg file without the sensitive info

**Comment by TehAkisGR** [comment]
Sure there you go

**Comment by TehAkisGR** [comment]
Sure there you go, also if you know if any of these scripts conflict with the esx_advancedgarage let me know 
[server.zip](https://github.com/HumanTree92/esx_advancedgarage/files/3610018/server.zip)

**Comment by lazosman** [comment]
is there a solution yet?

**Comment by HumanTree92** [comment]
Don't do the es_extended/client/functions. Just leave it all original and it should work.

**Comment by lazosman** [comment]
i still have the same problem, i did not changed the functions.lua, and still i have the same problem.. should i try the above solution?

**Comment by HumanTree92** [comment]
I will check to see if they changed anything. I would also make sure your using my vehicleshop_fix.sql

**Comment by lazosman** [comment]
after some research, i saw it conflicts with vMenu. If i disable vmenu, everything works. any solution?

**Comment by HumanTree92** [comment]
Has this issue been fixed for you?

**Comment by HumanTree92** [comment]
Closed due to no replies.
