### ISSUE TITLE
Storing damaged cars.

### ISSUE THREAD

**Issue by xdabeast** [HumanTree92/esx_advancedgarage#78]
Hey, i've been using your resource for a longtime but since this morning when people store a damaged car it comes out damaged.

**Comment by HumanTree92** [comment]
Also your comment doesn't make since. They store a damaged car & it comes out damaged???

**Comment by HumanTree92** [comment]
[Check the Wiki](https://github.com/HumanTree92/esx_advancedgarage/wiki)

**Comment by xdabeast** [comment]
Nvm, I did check the Wiki and I'll try that, i'll get back to you.
Sorry for any inconvenience.

**Comment by xdabeast** [comment]
I got another question for you, can I contact you outside here or just DM ?

**Comment by HumanTree92** [comment]
I have a discord that you can join and ask questions there if needed.
