### ISSUE TITLE
Vehicle Duplication Bug

### ISSUE THREAD

**Issue by generallee1994** [HumanTree92/esx_advancedgarage#79]
When you get a car out of the garage, it becomes immediately available in the Impound. You can therefore retrieve the same car from the impound indefinitely but you cannot store the duplicates or sell them. When the garage sets the car state to 0 the impound immediately thinks the car is impounded and never checks if the player has left the server. Is this normal behavior ? Absolutely no errors serverside or clientside, the database looks okay too. Appreciate any help.

**Comment by HumanTree92** [comment]
Read the fucking wiki.
