### ISSUE TITLE
No Vehicles In Garage

### ISSUE THREAD

**Issue by MeerkatRS** [HumanTree92/esx_advancedgarage#8]
![image](https://user-images.githubusercontent.com/31329492/53109672-47748900-3531-11e9-8ea8-81b5f53e21b2.png)
![image](https://user-images.githubusercontent.com/31329492/53110273-835c1e00-3532-11e9-92be-44d2187fe7e8.png)

I buy the vehicle and it's showing as owned in the database. It also stores it but when trying to pull out of garage says I have no vehicles in garage.

**Comment by HumanTree92** [comment]
Can you send me what u used for the config lines 14-38

**Comment by MeerkatRS** [comment]
![image](https://user-images.githubusercontent.com/31329492/53132609-1cf1f280-3568-11e9-8f6f-87900adbbfa7.png)
There ya go

**Comment by HumanTree92** [comment]
Hmm thats odd. There has to be more errors then 1 you posted above. Is there any more errors that pop up b/c the error above doesn't give me anything to go off of.

**Comment by MeerkatRS** [comment]
Thats the only error. It doesn't even show when I start the server only when I join the server. 
![image](https://user-images.githubusercontent.com/31329492/53140400-72d49380-3584-11e9-948d-8aba9e52484e.png)
This is the owned_vehicles structure if this helps?

**Comment by HumanTree92** [comment]
Not sure why but on mine vehicle & Job Null is No & on Default they are None

**Comment by MeerkatRS** [comment]
The latest esx_vehicleshop sql doesn't set them as null. I already tried switching vehicle to None but I'll try both.

**Comment by MeerkatRS** [comment]
![image](https://user-images.githubusercontent.com/31329492/53179709-2ae95700-35ec-11e9-86c2-2369a5110d61.png)
Can't even set job as none

**Comment by MeerkatRS** [comment]
If I set the job from none to unemployed it buys the car and actually shows my license when buying it. It also stores the car but can't see any cars in the garage list. If its set to none I can't even store the car.

**Comment by HumanTree92** [comment]
Yes that is correct. I am using the one from esx_vehicleshop.

**Comment by HumanTree92** [comment]
Quick question are you using the latest mysql?

**Comment by HumanTree92** [comment]
Also make sure your https://github.com/brouznouf/fivem-mysql-async & https://github.com/kanersps/esplugin_mysql & https://github.com/ESX-Org/async are fully updated.

**Comment by DarethZ33** [comment]
I didn't want to start up another thread, as I'm having the same issue. I've noticed that the ESX Vehicle Shop isn't saving the owned_vehicles information to the SQL database. On start-up however, I get this error message. [https://i.gyazo.com/296a51eb36971a606a20ca312e3bd75a.png](Screenshot of console)

**Comment by HumanTree92** [comment]
@DarethZ33 That Console Error is the same as https://github.com/HumanTree92/esx_advancedgarage/issues/7

Not sure whats causing it. Try to code i posted in the other issue.

**Comment by benzon** [comment]
The issue is the follow mysql statement, it checks for @job = '', it should deffently not do that, since right now the default value of vehicleshop should be null, and null wont translate in to ''
```lua
ESX.RegisterServerCallback('esx_advancedgarage:getOwnedCars', function(source, cb)
	local ownedCars = {}
	
	if Config.DontShowPoundCarsInGarage == true then
		MySQL.Async.fetchAll('SELECT * FROM owned_vehicles WHERE owner = @owner AND Type = @Type AND job = @job AND stored = @stored', {
			['@owner']  = GetPlayerIdentifiers(source)[1],
			['@Type']   = 'car',
			['@job']    = '',
			['@stored'] = true
		}, function(data)
			for _,v in pairs(data) do
				local vehicle = json.decode(v.vehicle)
				table.insert(ownedCars, {vehicle = vehicle, stored = v.stored, plate = v.plate})
			end
			cb(ownedCars)
		end)
	else
		MySQL.Async.fetchAll('SELECT * FROM owned_vehicles WHERE owner = @owner AND Type = @Type AND job = @job', {
			['@owner']  = GetPlayerIdentifiers(source)[1],
			['@Type']   = 'car',
			['@job']    = ''
		}, function(data)
			for _,v in pairs(data) do
				local vehicle = json.decode(v.vehicle)
				table.insert(ownedCars, {vehicle = vehicle, stored = v.stored, plate = v.plate})
			end
			cb(ownedCars)
		end)
	end
end)
```

The fix would be something like

```lua
ESX.RegisterServerCallback('esx_advancedgarage:getOwnedCars', function(source, cb)
	local ownedCars = {}
	
	if Config.DontShowPoundCarsInGarage == true then
		MySQL.Async.fetchAll('SELECT * FROM owned_vehicles WHERE owner = @owner AND Type = @Type AND job IS NULL AND stored = @stored', {
			['@owner']  = GetPlayerIdentifiers(source)[1],
			['@Type']   = 'car',
			['@stored'] = true
		}, function(data)
			for _,v in pairs(data) do
				local vehicle = json.decode(v.vehicle)
				table.insert(ownedCars, {vehicle = vehicle, stored = v.stored, plate = v.plate})
			end
			cb(ownedCars)
		end)
	else
		MySQL.Async.fetchAll('SELECT * FROM owned_vehicles WHERE owner = @owner AND Type = @Type AND job IS NULL', {
			['@owner']  = GetPlayerIdentifiers(source)[1],
			['@Type']   = 'car',
		}, function(data)
			for _,v in pairs(data) do
				local vehicle = json.decode(v.vehicle)
				table.insert(ownedCars, {vehicle = vehicle, stored = v.stored, plate = v.plate})
			end
			cb(ownedCars)
		end)
	end
end)
```
Or changing vehicleshops mysql witch is faulty right out of the gate.

Original
```sql
CREATE TABLE `owned_vehicles` (
	`owner` varchar(22) NOT NULL,
	`plate` varchar(12) NOT NULL,
	`vehicle` longtext,
	`type` VARCHAR(20) NOT NULL DEFAULT 'car',
	`job` VARCHAR(20) NOT NULL,
	`stored` TINYINT(1) NOT NULL DEFAULT '0',

	PRIMARY KEY (`plate`)
);
```
Issue with this is it dont allow job to be null or got a default value of ''
That will cause errors when buying a vehicle no matter what, since it's a flawed design, since there is no job set on normal cars...

The fix can be done to ways first way require this script to be updated, with the IS NULL change shown above.
```sql
CREATE TABLE `owned_vehicles` (
	`owner` varchar(22) NOT NULL,
	`plate` varchar(12) NOT NULL,
	`vehicle` longtext,
	`type` VARCHAR(20) NOT NULL DEFAULT 'car',
	`job` VARCHAR(20) NULL,
	`stored` TINYINT(1) NOT NULL DEFAULT '0',

	PRIMARY KEY (`plate`)
);
```

The easy fix
```sql
CREATE TABLE `owned_vehicles` (
	`owner` varchar(22) NOT NULL,
	`plate` varchar(12) NOT NULL,
	`vehicle` longtext,
	`type` VARCHAR(20) NOT NULL DEFAULT 'car',
	`job` VARCHAR(20) NOT NULL DEFAULT '',
	`stored` TINYINT(1) NOT NULL DEFAULT '0',

	PRIMARY KEY (`plate`)
);
```

**Comment by HumanTree92** [comment]
I will see what i can do. I would prefer instead of something blank like ' ' for it to be like none. Its a simple fix but currently dealing with other major matters that i am trying to fix.

**Comment by benzon** [comment]
@HumanTree92 related to this script or something else? if so do tell, im currently doing some changes to the script, that we use, so might be able to pitch in abit.

But ye this adleest gives a fix to thos hu have issues with this in the end, since the issue is not your script but a faulty .sql file from vehicleshop, did a PR with the Easy fix, since that would make sure it works with the garage.

**Comment by mifsopo** [comment]
i had this same exact problem but my simple fix was i just copied my database to look just like @HumanTree92  in his picture - https://imgur.com/OSUi8ya    i just unchecked all "Allow Null" Boxes and then it was good to go, easier fix than i thought, i also re arranged the order of my rows to be sure (not sure if it matters) but yea, that was the fix (i also still use the STATE row (if it even matters anymore )   https://imgur.com/8vd9h6I

**Comment by HumanTree92** [comment]
Hopefully fixed this issue with the latest update. If not please reopen this issue.

**Comment by BokyS** [comment]
Installed this resource today and have same problem.

**Comment by Samantha331** [comment]
how to you get to this table 
![image](https://user-images.githubusercontent.com/49114569/55291660-0c2a6d00-53af-11e9-8204-f66e68a32d97.png)

**Comment by Samantha331** [comment]
how do you get to this table https://imgur.com/OSUi8ya

**Comment by mifsopo** [comment]
@Samantha331  its in your database owned_vehicles is the table if im not mistaking?

**Comment by Samantha331** [comment]
@mifsopo nothing is there for me

**Comment by Samantha331** [comment]
nvm

**Comment by Samantha331** [comment]
![image](https://user-images.githubusercontent.com/49114569/55291687-76dba880-53af-11e9-92db-9de8637fc4d7.png)

**Comment by Samantha331** [comment]
that's is what is there for me

**Comment by mifsopo** [comment]
yes but @Samantha331 on your database you will have the data which is what your looking at but also the main configuration of the table for me its at the top middle of screen labled "Table:owned_vehicles"

**Comment by Samantha331** [comment]
@mifsopo yes i found it thanks

**Comment by LePlay1499** [comment]
I have also the same problem on a FiveM server from Zap Hosting. Sorry for my bad english i am a german guy.

**Comment by EraLucas** [comment]
Sorry to bright this up again but I edited my database with the suggestion but this bug still happen. I am also using Zap Hosting server.

**Comment by Thyke** [comment]
I found the solution. The vehicle row in the owned_vehicles table must be NOT_NULL

**Comment by Zitronenschaeler** [comment]
The problem is still. Can someone help?

**Comment by ADUPSxd** [comment]
So i had this issue as well, tried all 3 owned_vehicles tables (esx_vehicleshop and 2 from the supposed "fix" .sql file), but none worked, however, (in a way) combining both fixes actually fixed it for me.
`USE `essentialmode`;

CREATE TABLE `owned_vehicles` (
	`owner` varchar(22) NOT NULL,
	`plate` varchar(12) NOT NULL,
	`vehicle` longtext NOT NULL,
	`type` VARCHAR(20) NOT NULL DEFAULT 'car',
	`job` VARCHAR(20) NOT NULL DEFAULT '',
	`stored` TINYINT(1) NOT NULL DEFAULT '0',

	PRIMARY KEY (`plate`)
);`

**Comment by Zitronenschaeler** [comment]
@ADUPSxd Thanks for answer. But wer do you type in this 

    USE essentialmode;

    CREATE TABLE owned_vehicles (
    owner varchar(22) NOT NULL,
    plate varchar(12) NOT NULL,
    vehicle longtext NOT NULL,
    type VARCHAR(20) NOT NULL DEFAULT 'car',
    job VARCHAR(20) NOT NULL DEFAULT '',
    stored TINYINT(1) NOT NULL DEFAULT '0',

    PRIMARY KEY (plate)
    );

or have you import it into your owend_vehicles table?

**Comment by Frans29** [comment]
So where do i have to put this line of code??

**Comment by tahkanen** [comment]
i still have that error i dont see any cars on my garage but i see them in sql..

**Comment by gregor20021** [comment]
Ok so i found out what's the problem with my scripts after serching for a while. insteal of empty brackets or NULL my default value of job row on the vehicle in SQL should be civ as in civil.I searched trough the code and the same goes for boats,planes,. . . Hope i helped

**Comment by HumanTree92** [comment]
There is literally an sql in the download. And its noted in the wiki on how to fix this issue.
