### ISSUE TITLE
No need to be such a fucking twat.

### ISSUE THREAD

**Issue by generallee1994** [HumanTree92/esx_advancedgarage#80]
I asked a genuine question, no need to act like you are some kind of god. Get your ass off that high horse of yours before adressing people like fucking animals. Learn to have some fucking respect you worthless piece of shit.

**Comment by HumanTree92** [comment]
Yeah get blocked you fucking bitch. I am sick and tired of people asking the same damn Questions. Read the fucking readme.

**Comment by HumanTree92** [comment]
I hope u fucking die in your god damn sleep.

**Comment by HumanTree92** [comment]
Yeah come say that shit to me on discord you fucking pussy ass bitch.

**Comment by HumanTree92** [comment]
Fucking hope you die if you can't follow simple rules

**Comment by generallee1994** [comment]
Look at you all being triggered lmao. Discord ain't real life, which i suggest you get one of. Peace.

**Comment by HumanTree92** [comment]
Come on bitch dig a deeper whole. You gonna get banned from FiveM.

**Comment by HumanTree92** [comment]
I'm not triggered. I'm just sick and fucking tired of you fucking low life cunts like you who can't read the fucking Readme.

**Comment by HumanTree92** [comment]
Well people this is what you get when you don't read the Readme. People like this who think they are top shit & all they do is talk trash on platforms and can't say it to someone through voice or face to face is a fucking pussy. Kid thinks by just changing his info he can hide but he can't. I'm not triggered. Just simple read the fucking Readme. It says that if you can't follow the first rule expect a Rude Message and be blocked.

**Comment by HumanTree92** [comment]
Changed Name from generallee1994 to Ismael-J

**Comment by HumanTree92** [comment]
![69963031_2384438548483035_512979263062802432_n(1)](https://user-images.githubusercontent.com/16672252/64484086-efeaf180-d1d2-11e9-9285-5db42f75f7a9.png)
