### ISSUE TITLE
I have issue when the server reached 32

### ISSUE THREAD

**Issue by iRomario** [HumanTree92/esx_advancedgarage#81]
Hello sir , when the server reached 32/32 , i got an issue [MY SQL] get data from owned_vehicles | too many connections or connection timed out

**Comment by HumanTree92** [comment]
I would go to your mysql and allow more connections & increase the time out. Not sure where its at but use google to help you.

**Comment by iRomario** [comment]
:( , i don't know where is it in HiediSQL 
i google it but i didn't find it

**Comment by HumanTree92** [comment]
Depending on your hosting providing i'm not sure. If your not using your own Dedicated Server i would talk to your provider
