### ISSUE TITLE
Steam/License

### ISSUE THREAD

**Issue by Taker54** [HumanTree92/esx_advancedgarage#84]
How to use this script without steam, I just want to use it with rockstar

**Comment by Taker54** [comment]
esx_advancedgarage: license:0ba6f09429c2638632d61c41447883c0a0a3e63d attempted to store an vehicle they don't own!
A client has tried to authenticate using Steam, but `steam_webApiKey` is unset. Please set steam_webApiKey to a Steam Web API key as registered on Valve's https://steamcommunity.com/dev/apikey web page. Steam identifier information will be unavailable otherwise.
To suppress this message, `set steam_webApiKey "none"`.

**Comment by Taker54** [comment]
I already put that on the console and it does not come out, but at the time of putting the cars I see the following
esx_advancedgarage: license:0ba6f09429c2638632d61c41447883c0a0a3e63d attempted to store an vehicle they don't own!

**Comment by HumanTree92** [comment]
That is something you need to figure out on your own
