### ISSUE TITLE
Cars not registering

### ISSUE THREAD

**Issue by amerem3** [HumanTree92/esx_advancedgarage#87]
I can't get cars out of the garage/impound once they are stored

**Comment by HumanTree92** [comment]
Can you send an image of your owned_vehicles structure?

**Comment by amerem3** [comment]
https://imgur.com/vnw827S Im using another script right now but this is how my structure was setup

**Comment by HumanTree92** [comment]
Oh Well if your using a different script then close this issue. But that image is not the owned_vehicles structure. Your owned-Vehicle structure should look like https://camo.githubusercontent.com/a14d4d325a594efc425b1b4ffbe7220414de9571/68747470733a2f2f692e696d6775722e636f6d2f4f4933366e56332e706e67

**Comment by amerem3** [comment]
Thats exactly how my structure was

**Comment by HumanTree92** [comment]
I understand that but would prefer to see an actual image of the Structure b/c saying the sql is exactly like it doesn't give me nothing to go off of. An actual image would make things 100% easier to go off of. But if you don't want to upload the actual image of it then support for me won't happen since i have nothing to go off of. No errors or anything.

**Comment by Ex0r** [comment]
I'm having the same issue as the original poster. Owned cars can be stored, and the 'stored' column gets set to 1 as it should, but when you try to access the green circle it doesn't list the vehicles in the menu, and there is a client console log error attempting to index a nil value 'value'.

http://prntscr.com/pkbzkd

here's a printscreen of my structure

**Comment by HumanTree92** [comment]
Do you have an image of the Structure. Not the Data. The image you sent is the Data not structure. Here is mine for an example [Here](https://camo.githubusercontent.com/a14d4d325a594efc425b1b4ffbe7220414de9571/68747470733a2f2f692e696d6775722e636f6d2f4f4933366e56332e706e67)

**Comment by Ex0r** [comment]
Whoops, I linked the wrong screenshot. Here you go:

http://prntscr.com/pkkdw6

**Comment by Ex0r** [comment]
Any update on this? Not seeing why this is happening.

**Comment by HumanTree92** [comment]
Yeah idk. I would read through the wiki and see if anything in there helps. But other then that i have no clue. Works fine for me & many others.

**Comment by ThePinkPanda** [comment]
I have the same issue, could you tell me which plugin/mod you use to store the cars?

**Comment by oktan1337** [comment]
Same issue here, cant seem to get it working mine looks the same
https://gyazo.com/5251f1e16d295b5d42906393b67620a1

**Comment by ValentijnSlijper** [comment]
Yea again Joey,
I contacted you through email the other day and you told me to contacted you here... 
 So as I told you before upon storing my cars in the garage I can't get them out. And it says "You don't have any cars.." 
Img of database and in game: https://imgur.com/a/Bt2hQpB

Sadly I am new to Fivem and creating Fivem server so I am not really experienced. 

I hope you can help tnx in advance.

Valentijn Slijper

**Comment by HumanTree92** [comment]
These issues can be resolved by Deleting the Current owned_vehicles then importing my vehicleshop_fix.sql
