### ISSUE TITLE
vehicle_names.lua some work, some don’t

### ISSUE THREAD

**Issue by gilangmgs** [HumanTree92/esx_advancedgarage#90]
Hello.
I have issues with vehicle_names.lua. 
there are some cars that are still null names, even though I already put it in vehicle_names.lua.
what's the solution?
thanks

**Comment by HumanTree92** [comment]
Can u upload the vehicle_names.lua

**Comment by gilangmgs** [comment]
function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
AddTextEntry('16challenger', 'Dodge Challenger 2016')
AddTextEntry('16charger', 'Dodge Charger')
AddTextEntry('17m760i', '760i')
AddTextEntry('180sxrb', 'Nissan 180sx RB')
AddTextEntry('19S650', 'S650 Maybach')
AddTextEntry('19gt500', 'Ford Shelby')
AddTextEntry('20f250', 'F 250')
AddTextEntry('20r1', 'Yamaha R1')
AddTextEntry('488misha', 'Ferrari 488misha')
AddTextEntry('2f2fgts', 'Eclipse GSX ff1')
AddTextEntry('2f2fmk4', 'Supra ff1')
AddTextEntry('2f2fmle7', 'Lancer ff1')
AddTextEntry('911turbos', '911 Turbo')
AddTextEntry('AKUMA', 'CBR 250RR')
AddTextEntry('BUGATTI', 'Bugatti ')
AddTextEntry('Lectro', 'BMW R-75 Bobber')
AddTextEntry('RAPTOR150', 'Ford Raptor')
AddTextEntry('africat', 'CRF 1000')
AddTextEntry('avarus', 'Avarus')
AddTextEntry('bagger', 'Bagger')
AddTextEntry('baller3', 'Baller Sport')
AddTextEntry('bati', 'Bati 801')
AddTextEntry('bati2', 'Bati 801RR')
AddTextEntry('bbentayga', 'Bentley Bentayga')
AddTextEntry('bc', 'bc')
AddTextEntry('bf400', 'BF400')
AddTextEntry('bifta', 'Bifta')
AddTextEntry('bison', 'Bison')
AddTextEntry('blade', 'Blade')
AddTextEntry('blazer4', 'Blazer Sport')
AddTextEntry('blista2', 'Civic 90')
AddTextEntry('bmci', 'M5')
AddTextEntry('bmm', 'Bentley Mulsanne')
AddTextEntry('bmws', 'BMW 1000s')
AddTextEntry('bmx', 'BMX (velo)')
AddTextEntry('brawler', 'Brawler')
AddTextEntry('buccaneer', 'Buccaneer')
AddTextEntry('buccaneer2', 'Buccaneer Rider')
AddTextEntry('buffalo', 'A4')
AddTextEntry('c7', 'Corvette C7')
AddTextEntry('carbonizzare', 'Carbonizzare')
AddTextEntry('carbonrs', 'Carbon RS')
AddTextEntry('casco', 'Casco')
AddTextEntry('cb500f', 'CB 500f')
AddTextEntry('celica', 'Celica')
AddTextEntry('chargerf8', 'Dodge FS')
AddTextEntry('chimera', 'Chimera')
AddTextEntry('chino', 'Chino')
AddTextEntry('chino2', 'Chino Luxe')
AddTextEntry('chiron', 'Bugatti Chiron')
AddTextEntry('cliffhanger', 'Cliffhanger')
AddTextEntry('comet2', 'Comet')
AddTextEntry('comet5', 'Comet 5')
AddTextEntry('contender', 'Contender')
AddTextEntry('contgt13', 'contgt13')
AddTextEntry('coquette', 'Coquette')
AddTextEntry('coquette2', 'Coquette Classic')
AddTextEntry('coquette3', 'Coquette BlackFin')
AddTextEntry('cruiser', 'Cruiser (velo)')
AddTextEntry('cu2', 'Accord 2010')
AddTextEntry('d99', 'd99')
AddTextEntry('daemon', 'Daemon')
AddTextEntry('daemon2', 'Daemon High')
AddTextEntry('db11', 'Aston MArtin DB11')
AddTextEntry('defiler', 'Defiler')
AddTextEntry('demonhawk', 'SRT Demonhawk')
AddTextEntry('diavel', 'Ducatti Diavel')
AddTextEntry('dominator', 'Dominator')
AddTextEntry('double', 'Double T')
AddTextEntry('dubsta', 'G65')
AddTextEntry('dubsta2', 'Dubsta Luxuary')
AddTextEntry('dubsta3', 'Bubsta 6x6')
AddTextEntry('dukes', 'Dukes')
AddTextEntry('enduro', 'Enduro')
AddTextEntry('esskey', 'Esskey')
AddTextEntry('exemplar', 'Camry')
AddTextEntry('expedition', 'Expedition')
AddTextEntry('faction', 'Faction')
AddTextEntry('faction2', 'Faction Rider')
AddTextEntry('faction3', 'Faction XL')
AddTextEntry('faggio', 'Faggio')
AddTextEntry('faggio2', 'Vespa')
AddTextEntry('fct', 'California')
AddTextEntry('felon', 'Felon')
AddTextEntry('feltzer3', 'Stirling GT')
AddTextEntry('fixter', 'Fixter (velo)')
AddTextEntry('fmj', 'FMJ')
AddTextEntry('fnf4r34', 'Skyline R34 ff1')
AddTextEntry('fnfmits', 'Eclipse GSX ff2')
AddTextEntry('fnfmk4', 'Supra ff2')
AddTextEntry('fnfrx7', 'Mazda RX7 ff1')
AddTextEntry('futo', 'Karin Futo')
AddTextEntry('fxxk16', 'Ferarri Corse Clienti')
AddTextEntry('gargoyle', 'Gargoyle')
AddTextEntry('gauntlet', 'Gauntlet')
AddTextEntry('gburrito', 'Gang Burrito')
AddTextEntry('gburrito2', 'Burrito 2')
AddTextEntry('goldwing', 'Goldwing')
AddTextEntry('gpz1100', 'Kawasaki GPZ1100')
AddTextEntry('granger', 'Grabger')
AddTextEntry('gsxr', 'Suzuki GSX 1000')
AddTextEntry('gt500', 'GT 500')
AddTextEntry('gtr', 'GTR')
AddTextEntry('gtrnismo17', 'GTR Nismo')
AddTextEntry('guardian', 'Guardian')
AddTextEntry('h2carb', 'Kawasaki H2RR')
AddTextEntry('hakuchou', 'Yamaha FJR1300')
AddTextEntry('hakuchou2', 'Hakuchou Sport')
AddTextEntry('hcbr17', 'CBR 1000RR')
AddTextEntry('hermes', 'Hermes')
AddTextEntry('hexer', 'Hexer')
AddTextEntry('hondacivictr', 'Civic Turbo 2018')
AddTextEntry('honody', 'Odyssey')
AddTextEntry('hotknife', 'Hotknife')
AddTextEntry('huracan', 'Lamborghini Huracán')
AddTextEntry('hustler', 'Hustler')
AddTextEntry('hvrod', 'Harley Davidson')
AddTextEntry('innovation', 'Innovation')
AddTextEntry('issi2', 'Issi')
AddTextEntry('italia458', 'Ferarri Italia 458')
AddTextEntry('jackal', 'Jackal')
AddTextEntry('jester2', 'Jester(Racecar)')
AddTextEntry('jp12', 'Rubicon 4 Door')
AddTextEntry('kamacho', 'Kamacho')
AddTextEntry('kr150', 'kr150')
AddTextEntry('kuruma', 'Lancer Evo X')
AddTextEntry('ladybird6str', 'VW Kodok')
AddTextEntry('lc500', 'Lexus LC 500')
AddTextEntry('lp700r', '700r')
AddTextEntry('lp770', '770')
AddTextEntry('lwalk458', 'Ferarri Italia 458 RB')
AddTextEntry('m4f82', 'M4')
AddTextEntry('m6gc', 'M6')
AddTextEntry('mamba', 'Mamba')
AddTextEntry('manchez', 'Manchez')
AddTextEntry('massacro2', 'Massacro(Racecar)')
AddTextEntry('mers63c', 'C63')
AddTextEntry('mesa', 'Mesa')
AddTextEntry('mesa3', 'Mesa Trail')
AddTextEntry('moonbeam', 'Alphard')
AddTextEntry('moonbeam2', 'Moonbeam Rider')
AddTextEntry('mvisiongt', 'Mercedez Benz Hybrid')
AddTextEntry('nemesis', 'Nemesis')
AddTextEntry('neon', 'Neon')
AddTextEntry('nightblade', 'Nightblade')
AddTextEntry('nightshade', 'Nightshade')
AddTextEntry('nissantitan17', 'Titan 2017')
AddTextEntry('omnis', 'Omnis')
AddTextEntry('oracle2', 'Oracle XS')
AddTextEntry('p1', 'McLaren P1')
AddTextEntry('panigale', 'panigale')
AddTextEntry('pariah', 'Pariah')
AddTextEntry('patriot', 'Patriot')
AddTextEntry('pcj', 'PCJ-600')
AddTextEntry('pfister811', 'Pfister')
AddTextEntry('phoenix', 'Phoenix')
AddTextEntry('picador', 'Picador')
AddTextEntry('primo', 'S600')
AddTextEntry('primo2', 'Primo Custom')
AddTextEntry('r25', 'r25')
AddTextEntry('r8ppi', 'R8')
AddTextEntry('r8v10abt', 'R8 Sport')
AddTextEntry('raiden', 'raiden')
AddTextEntry('rapidgt2', 'Rapid GT Convertible')
AddTextEntry('rapidgt3', 'Rapid GT3')
AddTextEntry('rc', 'KTM RC 390')
AddTextEntry('reaper', 'Reaper')
AddTextEntry('rebel2', 'Rebel')
AddTextEntry('retinue', 'Retinue')
AddTextEntry('riata', 'riata')
AddTextEntry('rm3e36', 'M3 RB')
AddTextEntry('rmodbmwi8', 'i8')
AddTextEntry('rmodgt63', 'Mercedez Benz AMG GT')
AddTextEntry('rmodm4gts', 'M4 S')
AddTextEntry('rmodmustang', 'Ford Mustang GT')
AddTextEntry('rmodveneno', 'Lamborghini Veneno')
AddTextEntry('rmodx6', 'X6')
AddTextEntry('rs6', 'RS6 2016')
AddTextEntry('rs7', 'RS7 2016')
AddTextEntry('ruffian', 'Ruffian')
AddTextEntry('rumpo3', 'Rumpo Trail')
AddTextEntry('s15rb', 'Silvia RB')
AddTextEntry('sabregt', 'Sabre Turbo')
AddTextEntry('sabregt2', 'Sabre GT')
AddTextEntry('sanchez', 'Sanchez')
AddTextEntry('sanchez2', 'Sanchez Sport')
AddTextEntry('sandking', 'Sandking')
AddTextEntry('sc1', 'SC 1')
AddTextEntry('sc18', 'Lamborghini SC18 Alston')
AddTextEntry('schafter2', 'S300')
AddTextEntry('schafter3', 'AMG REP')
AddTextEntry('scorcher', 'Scorcher velo')
AddTextEntry('senna', 'senna')
AddTextEntry('sentinel2', 'Sentinel XS')
AddTextEntry('sentinel3', 'Sentinel3')
AddTextEntry('serv_electricscooter', 'Scooter Electric')
AddTextEntry('shotaro', 'Shotaro Concept')
AddTextEntry('slamvan3', 'Slam Van')
AddTextEntry('sovereign', 'Sovereign')
AddTextEntry('srt8', 'SRT')
AddTextEntry('stretch', 'Stretch')
AddTextEntry('sultanrs', 'Sultan RS')
AddTextEntry('superd', 'Super Diamond')
AddTextEntry('supra2', 'Supra')
AddTextEntry('surfer', 'Surfer')
AddTextEntry('tahoe', 'Tahoe')
AddTextEntry('tailgater', 'Tailgater')
AddTextEntry('tampa', 'Tampa')
AddTextEntry('tampa2', 'Drift Tampa')
AddTextEntry('tancrx', 'CRX')
AddTextEntry('thrust', 'Thrust')
AddTextEntry('toros', 'Toros')
AddTextEntry('trailcat', 'Rubicon Extrem')
AddTextEntry('tribike3', 'Tri bike velo')
AddTextEntry('trophytruck', 'Trophy Truck')
AddTextEntry('trophytruck2', 'Trophy Truck Limited')
AddTextEntry('trr', 'KTM Supermoto')
AddTextEntry('turismor', 'Turismo R')
AddTextEntry('urus', 'Urus')
AddTextEntry('vacca', 'Vacca')
AddTextEntry('vader', 'Vader')
AddTextEntry('vigero', 'Vigero')
AddTextEntry('vindicator', 'Honda NM4 Vultus')
AddTextEntry('virgo', 'Virgo')
AddTextEntry('viseris', 'Viseris')
AddTextEntry('visione', 'Visione')
AddTextEntry('voodoo', 'Voodoo')
AddTextEntry('vortex', 'Vortex')
AddTextEntry('warrener', 'Warrener')
AddTextEntry('windsor', 'Windsor')
AddTextEntry('windsor2', 'Windsor Drop')
AddTextEntry('wmfenyr', 'Fenyr Supersport')
AddTextEntry('wolfsbane', 'Woflsbane')
AddTextEntry('xls', 'XLS')
AddTextEntry('yosemite', 'Yosemite')
AddTextEntry('yzfr6', 'Yahama R6')
AddTextEntry('yzfsm', 'Yamaha Supermoto')
AddTextEntry('z1000a1', 'Kawasaki Z1000')
AddTextEntry('zentorno', 'Zentorno')
AddTextEntry('zion', 'Zion')
AddTextEntry('zl12017', 'Camaro ZL1')
AddTextEntry('zombiea', 'Zombie')
AddTextEntry('zombieb', 'Zombie Luxuary')
end)

**Comment by HumanTree92** [comment]
Do u know which ones do & which ones don't?

**Comment by gilangmgs** [comment]
one example.
this AddTextEntry('nissantitan17', 'Titan 2017')

**Comment by HumanTree92** [comment]
Yeah i'm not 100% sure why it wouldn't be working. I have had a few problems with vehicles not showing up. 

One thing that i did find out is on the vehicles with long names is change the model name to a max of 10 Characters. For example i had a kenwortht700s & changed everything to kenwort70s. After that the vehicle name started working perfectly.

If your still having problems i suggest a simple [Google Search](https://www.google.com/search?safe=off&sxsrf=ACYBGNREHkKSuY_NOJsGm0c3HoGwb6i7Kw%3A1573390256482&ei=sAfIXar8HPCg_QbwsLygAw&q=FiveM+vehicle_names.lua&oq=FiveM+vehicle_names.lua&gs_l=psy-ab.3...0.0..56833...0.0..0.0.0.......0......gws-wiz.ocNFU_bG5r8&ved=0ahUKEwiqlNK619_lAhVwUN8KHXAYDzQQ4dUDCAo&uact=5) or try searching on [FiveM](https://forum.fivem.net/search?q=vehicle_names.lua)

Other then that there isn't much help that i can give. And since this isn't an issue with this Script i am going to close this issue. You can still comment and i will try & help further but try the links posted above b/c i am busy most of the time.
