### ISSUE TITLE
No cars in impound

### ISSUE THREAD

**Issue by Knasqt** [HumanTree92/esx_advancedgarage#91]
I cant see my cars in impound... Police and Ems can just not civs

**Comment by HumanTree92** [comment]
Without anymore info to go off of i can't help.

**Comment by Knasqt** [comment]
Like i will go pull out a car as a civ and go to an impound and its not there... For cops and ems it works fine tho. 

When i go to the Impound there is just no cars there but i have cars out of my garage

**Comment by Knasqt** [comment]
You can see that i have a car out of my garage but it doesn't show up in impound this is with all cars not just add on cars 

https://gyazo.com/c595817c0df704ff25aacf68f30ee04c

**Comment by HumanTree92** [comment]
Like I said. If there is no error in the console or in f8 there isntuch I can do. This works 100% for most people who know what they r doing. But can u please send me an image of ur owned_vehicles structure.

**Comment by HumanTree92** [comment]
Please be patient. My replies will be slow for the rest of the month as I am on vacation till December.

**Comment by HumanTree92** [comment]
Please post an image of your owned_vehicles structure. If you haven't already please make sure you are using my vehicleshop_fix.sql which will replace your current owned_vehicles.

**Comment by Nightkiller1** [comment]
im having the exact same issue, garage works great but if a car despawns or gets impounded it just goes nowhere. only why they come back is if a server restart then they all go back in the garage

**Comment by HumanTree92** [comment]
Can't help if you people would understand that the first step is to post an image of your owned_vehicles & to make sure you are using my vehicleshop_fix.sql
