### ISSUE TITLE
Impound

### ISSUE THREAD

**Issue by Kayjewlers12** [HumanTree92/esx_advancedgarage#94]
When i pull out a car it doesn't go to impound. This problem is only for the Civ Impound the Police and EMS impound work fine. Not sure what causes this problem but what from what ive seen its a common issue... Do we have a fix for this yet?

Thank you

**Comment by HumanTree92** [comment]
It's not a common issue. Bc it works 100% fine. Please post image of ur owned_vehicles structure & any errors in the console.

**Comment by HumanTree92** [comment]
Please be patient. My replies will be slow for the rest of the month as I am on vacation till December.

**Comment by Kayjewlers12** [comment]
https://gyazo.com/68c212b38f53ac07e4e00e20ac2dff8f

no worries man have fun!

**Comment by Kayjewlers12** [comment]
https://gyazo.com/51fd4a5aecae902899c2b88df7c12d28 This is my structure... Sorry 
Also there is no errors in the console.

**Comment by Kayjewlers12** [comment]
I have fixed this issue... for anyone else having this 

Just Copy his exact Owned_vehicle structure which you can find here 
https://imgur.com/OSUi8ya
