### ISSUE TITLE
Error. And vehicles cant be Displayed

### ISSUE THREAD

**Issue by SleepeXapu** [HumanTree92/esx_advancedgarage#96]
I Have some Problems with the Garage Vehicles i own cant be displayed The error it gives to me is 
```
 SCRIPT ERROR: @esx_advancedgarage/server/main.lua:349: attempt to index a nil value (local 'account')
 ref (@esx_advancedgarage/server/main.lua:349)
 handler (@esx_addonaccount/server/main.lua:63)
 handler (@esx_advancedgarage/server/main.lua:348)
```

Any possible ideas how to fix?

**Comment by HumanTree92** [comment]
Please be patient. My replies will be slow for the rest of the month as I am on vacation till December.

**Comment by t-poeschl** [comment]
Same here

**Comment by HumanTree92** [comment]
Make sure u both have esx_addonaccount. Also put this script at the end of all the esx scripts. There might be a problem with either A. Not having esx_addonaccount or B. A load order problem. 

I am currently away on vacation so I don't have the files or a computer near me.

**Comment by t-poeschl** [comment]
I tried, but also the problem

**Comment by HumanTree92** [comment]
Ok I see the problem but there isn't a way for me to fix it from my phone. Just comment out the all the lines the deal with Triggerevent esx_addonaccount in the server file.

**Comment by HumanTree92** [comment]
I'm pretty sure the problem is with society_mecano. Change that to whatever society account is in ur database.

**Comment by HumanTree92** [comment]
If that doesn't work just remove the triggerevents.

**Comment by t-poeschl** [comment]
I got it, how you said, its with the society_mecano, you need to change it to society_mechanic

**Comment by HumanTree92** [comment]
Yeah that's my mistake. I will fix that when I get home. I seen the problem. I still have the old society not the new one. So change all of those and it should work.

**Comment by t-poeschl** [comment]
You havent anything todo with esx_property or?

**Comment by HumanTree92** [comment]
Esx_property is needed if u have it set to use house garages.

**Comment by t-poeschl** [comment]
Yeah but i cant open the Deposit on the Properties
there are some Clientside error with the blackmoney

**Comment by HumanTree92** [comment]
Is it an error with this script or another?

**Comment by tpoeschldk** [comment]
https://github.com/ESX-Org/esx_property/issues/79
This here

**Comment by SleepeXapu** [comment]
Fixed. I deleted "owned_vehicles" from the database used the vehicleshop_fix.sql restarted the server and it worked ;D

**Comment by pakjohnweck** [comment]
my error is SCRIPT ERROR: @esx_advancedgarag/client/main.lua.208:  Attempt to index a nil value (field 'value') any idea why i need help.
