### ISSUE TITLE
Cars still not repaired out of garage

### ISSUE THREAD

**Issue by Patrickstek121** [HumanTree92/esx_advancedgarage#98]
when i pay for repair in the garage and i get my car back it is still not repaired

I have the last version

**Comment by HumanTree92** [comment]
Custom Vehicle or Default Vehicle. If a default vehicle please give me the name.

**Comment by Danny9865** [comment]
@HumanTree92 Also have the same issue mate, it appears to be all cars not just a select few, i tested this on quite a few cars/bikes. It will charge you to put the vehicle away but you can pull the vehicle out again and instantly store it and it will charge you the same amount because its still damaged to the amount it was before.

**Comment by Danny9865** [comment]
ESX.TriggerServerCallback('esx_advancedgarage:getOwnedCars', function(ownedCars)
		if #ownedCars == 0 then
			ESX.ShowNotification(_U('garage_nocars'))
		else
			for _,v in pairs(ownedCars) do
				if Config.UseVehicleNamesLua then
					local hashVehicule = v.vehicle.model
					local aheadVehName = GetDisplayNameFromVehicleModel(hashVehicule)
					local vehicleName  = GetLabelText(aheadVehName)
					local plate        = v.plate
					local vehDamage	   = math.floor(v.vehicle.health/10)
					local labelvehicle
					
					if Config.ShowVehicleLocation then
						if v.stored then
							labelvehicle = '| '..plate..' | '..vehicleName..' | '.._U('loc_garage')..' | '..vehDamage..'% '
						else
							labelvehicle = '| '..plate..' | '..vehicleName..' | '.._U('loc_pound')..' | '..vehDamage..'% '
						end
					else
						if v.stored then
							labelvehicle = '| '..plate..' | '..vehicleName..' | '..vehDamage..'% '
						else
							labelvehicle = '| '..plate..' | '..vehicleName..' | '..vehDamage..'% '
						end
					end
					
					table.insert(elements, {label = labelvehicle, value = v})
				else
					local hashVehicule = v.vehicle.model
					local vehicleName  = GetDisplayNameFromVehicleModel(hashVehicule)
					local plate        = v.plate
					local vehDamage	   = math.floor(v.vehicle.health/10)
					local labelvehicle
					
					if Config.ShowVehicleLocation then
						if v.stored then
							labelvehicle = '| '..plate..' | '..vehicleName..' | '.._U('loc_garage')..' | '..vehDamage..'% '
						else
							labelvehicle = '| '..plate..' | '..vehicleName..' | '.._U('loc_pound')..' | '..vehDamage..'% '
						end
					else
						if v.stored then
							labelvehicle = '| '..plate..' | '..vehicleName..' | '..vehDamage..'% '
						else
							labelvehicle = '| '..plate..' | '..vehicleName..' | '..vehDamage..'% '
						end
					end
					
					
					table.insert(elements, {label = labelvehicle, value = v})
				end
			end
		end

**Comment by Danny9865** [comment]
amended you code to this, makes a nice addition if you take out the garage repair side

**Comment by bengeminiani** [comment]
having the same problem. when i am trying to put a vehicle in the garage it charges me. but the vehicles do not get repaired. any solution?

**Comment by Danny9865** [comment]
well for the meantime as a workaround ive just took the billing part out, and im going to rely on the RP of the mechanics but its up to you.

-- Store Owned Cars Menu
function StoreOwnedCarsMenu()
	local playerPed  = GetPlayerPed(-1)
	if IsPedInAnyVehicle(playerPed,  false) then
		local playerPed    = GetPlayerPed(-1)
		local coords       = GetEntityCoords(playerPed)
		local vehicle      = GetVehiclePedIsIn(playerPed, false)
		local vehicleProps = ESX.Game.GetVehicleProperties(vehicle)
		local current 	   = GetPlayersLastVehicle(GetPlayerPed(-1), true)
		local engineHealth = GetVehicleEngineHealth(current)
		local plate        = vehicleProps.plate
		
		ESX.TriggerServerCallback('esx_advancedgarage:storeVehicle', function(valid)
			if valid then
				putaway(vehicle, vehicleProps)
			else
				ESX.ShowNotification(_U('cannot_store_vehicle'))
			end
		end, vehicleProps)
	else
		ESX.ShowNotification(_U('no_vehicle_to_enter'))
	end
end

^^^ that makes it so it doesn't bill you

**Comment by bengeminiani** [comment]
if i put that code it wont store the car.

**Comment by Danny9865** [comment]
yeh i deleted them, tested in two servers, worked in one and not the other so it isn't reliable. Back to square one, potentially have to look at a different script if this doesn't start repairing cars.

**Comment by HumanTree92** [comment]
You can simply not use the repair side & require people to take it to a Mechanic or have them repair it themselves before storing it. I will add a few options in the next few days

**Comment by XvenDeR** [comment]
![image](https://user-images.githubusercontent.com/29688478/73066794-aa903d80-3eaf-11ea-8b45-5ff514647f9d.png)
indeed some modded cars comes out broken. solution?

**Comment by XvenDeR** [comment]
Now it gets weird, removed repair function and removed setHealth to 1000, now only some modded cars saves health, but all other comes with full health of engine even if I broke it. Wth?

**Comment by XvenDeR** [comment]
Even tried to put some extra
`SetVehicleEngineHealth(vehicle,1000)`
in repair function and spawn... no success, weirdest thing....

**Comment by HumanTree92** [comment]
Should be fixed in b09593847ec61bd6292708f11b4ae8fd1b7e37f9

**Comment by Patrickstek121** [comment]
Yeah its fixed :) Thanks @HumanTree92

**Comment by Patrickstek121** [comment]
I have another problem with this fix. When i use it and change every vehicle to job "civ" players get a connection intterupted. When i disable the new one and start the old when nobody have issues. ....?
