### ISSUE TITLE
stored vehicles not accessable and do not dissapear

### ISSUE THREAD

**Issue by numpty9989** [HumanTree92/esx_advancedgarage#99]
I bought a car and took it to the garage them pressed return it said your vehicle has been stored or something yet it was still next to me... then I go back to the garage and list my vehicles and it showed out. i log off and back in and the car has disappeared.,. then check the garage and still says out.,.. I was the ONLY person on the server. any help is appreciated..

**Comment by HumanTree92** [comment]
Can you repeat your question. With what i am understanding is your saying "You bought a car & took it to the Garage. You pressed return it & it said your vehicle has been stored." Not sure what you mean by "or something yet it was still next to me... ".

**Comment by numpty9989** [comment]
Yeah basically I buy a car go to store it and the car stays beside me yet says its stored. And if I go back to garage and check list it's out in world.. there is no way to store it.. I turned off stock esx garage to use this also and tried with original sql and the ones included

**Comment by HumanTree92** [comment]
Make sure your server & scripts are updated is a start. If you know that every thing is update please check your server logs & client logs for any errors.

**Comment by numpty9989** [comment]
They're all updated they were all downloaded yesterday

**Comment by HumanTree92** [comment]
Alright. Check your Server & Client Logs for any Errors.

**Comment by numpty9989** [comment]
Have done there are no errors with esx or other scripts
